//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/ling/tokensregex/CoreMapSequenceMatchAction.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction")
#ifdef RESTRICT_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction
#define INCLUDE_ALL_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction 0
#else
#define INCLUDE_ALL_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction 1
#endif
#undef RESTRICT_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction
#ifdef INCLUDE_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction
#define INCLUDE_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction 1
#endif
#ifdef INCLUDE_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_AnnotateAction
#define INCLUDE_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction 1
#endif

#if !defined (EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_) && (INCLUDE_ALL_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction || defined(INCLUDE_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction))
#define EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_

#define RESTRICT_EduStanfordNlpLingTokensregexSequenceMatchAction 1
#define INCLUDE_EduStanfordNlpLingTokensregexSequenceMatchAction 1
#include "edu/stanford/nlp/ling/tokensregex/SequenceMatchAction.h"

@class EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction;

@interface EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction : NSObject < EduStanfordNlpLingTokensregexSequenceMatchAction >

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_STATIC_INIT(EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction)

inline EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction *EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_get_DEFAULT_MERGE_ACTION();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction *EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_DEFAULT_MERGE_ACTION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction, DEFAULT_MERGE_ACTION, EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction *)

FOUNDATION_EXPORT void EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_init(EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction *self);

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction)

#endif

#if !defined (EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_AnnotateAction_) && (INCLUDE_ALL_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction || defined(INCLUDE_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_AnnotateAction))
#define EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_AnnotateAction_

@class IOSIntArray;
@protocol EduStanfordNlpLingTokensregexSequenceMatchResult;
@protocol JavaUtilMap;

@interface EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_AnnotateAction : EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction {
 @public
  id<JavaUtilMap> attributes_;
}

#pragma mark Public

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)attributes;

- (id<EduStanfordNlpLingTokensregexSequenceMatchResult>)applyWithEduStanfordNlpLingTokensregexSequenceMatchResult:(id<EduStanfordNlpLingTokensregexSequenceMatchResult>)matchResult
                                                                                                     withIntArray:(IOSIntArray *)groups;

@end

J2OBJC_EMPTY_STATIC_INIT(EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_AnnotateAction)

J2OBJC_FIELD_SETTER(EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_AnnotateAction, attributes_, id<JavaUtilMap>)

FOUNDATION_EXPORT void EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_AnnotateAction_initWithJavaUtilMap_(EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_AnnotateAction *self, id<JavaUtilMap> attributes);

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_AnnotateAction *new_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_AnnotateAction_initWithJavaUtilMap_(id<JavaUtilMap> attributes) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_AnnotateAction *create_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_AnnotateAction_initWithJavaUtilMap_(id<JavaUtilMap> attributes);

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_AnnotateAction)

#endif

#if !defined (EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction_) && (INCLUDE_ALL_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction || defined(INCLUDE_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction))
#define EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction_

@class EduStanfordNlpPipelineCoreMapAggregator;
@class IOSIntArray;
@protocol EduStanfordNlpLingTokensregexSequenceMatchResult;

@interface EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction : EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction {
 @public
  EduStanfordNlpPipelineCoreMapAggregator *aggregator_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithEduStanfordNlpPipelineCoreMapAggregator:(EduStanfordNlpPipelineCoreMapAggregator *)aggregator;

- (id<EduStanfordNlpLingTokensregexSequenceMatchResult>)applyWithEduStanfordNlpLingTokensregexSequenceMatchResult:(id<EduStanfordNlpLingTokensregexSequenceMatchResult>)matchResult
                                                                                                     withIntArray:(IOSIntArray *)groups;

@end

J2OBJC_EMPTY_STATIC_INIT(EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction)

J2OBJC_FIELD_SETTER(EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction, aggregator_, EduStanfordNlpPipelineCoreMapAggregator *)

FOUNDATION_EXPORT void EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction_init(EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction *self);

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction *new_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction *create_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction_init();

FOUNDATION_EXPORT void EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction_initWithEduStanfordNlpPipelineCoreMapAggregator_(EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction *self, EduStanfordNlpPipelineCoreMapAggregator *aggregator);

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction *new_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction_initWithEduStanfordNlpPipelineCoreMapAggregator_(EduStanfordNlpPipelineCoreMapAggregator *aggregator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction *create_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction_initWithEduStanfordNlpPipelineCoreMapAggregator_(EduStanfordNlpPipelineCoreMapAggregator *aggregator);

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction_MergeAction)

#endif

#pragma pop_macro("INCLUDE_ALL_EduStanfordNlpLingTokensregexCoreMapSequenceMatchAction")
