//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/international/Language.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduStanfordNlpInternationalLanguage")
#ifdef RESTRICT_EduStanfordNlpInternationalLanguage
#define INCLUDE_ALL_EduStanfordNlpInternationalLanguage 0
#else
#define INCLUDE_ALL_EduStanfordNlpInternationalLanguage 1
#endif
#undef RESTRICT_EduStanfordNlpInternationalLanguage

#if !defined (EduStanfordNlpInternationalLanguage_) && (INCLUDE_ALL_EduStanfordNlpInternationalLanguage || defined(INCLUDE_EduStanfordNlpInternationalLanguage))
#define EduStanfordNlpInternationalLanguage_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;
@protocol EduStanfordNlpParserLexparserTreebankLangParserParams;

typedef NS_ENUM(NSUInteger, EduStanfordNlpInternationalLanguage_Enum) {
  EduStanfordNlpInternationalLanguage_Enum_Any = 0,
  EduStanfordNlpInternationalLanguage_Enum_Arabic = 1,
  EduStanfordNlpInternationalLanguage_Enum_Chinese = 2,
  EduStanfordNlpInternationalLanguage_Enum_English = 3,
  EduStanfordNlpInternationalLanguage_Enum_German = 4,
  EduStanfordNlpInternationalLanguage_Enum_French = 5,
  EduStanfordNlpInternationalLanguage_Enum_Hebrew = 6,
  EduStanfordNlpInternationalLanguage_Enum_Spanish = 7,
  EduStanfordNlpInternationalLanguage_Enum_UniversalEnglish = 8,
  EduStanfordNlpInternationalLanguage_Enum_Unknown = 9,
};

@interface EduStanfordNlpInternationalLanguage : JavaLangEnum < NSCopying > {
 @public
  id<EduStanfordNlpParserLexparserTreebankLangParserParams> params_;
}

#pragma mark Public

- (jboolean)compatibleWithWithEduStanfordNlpInternationalLanguage:(EduStanfordNlpInternationalLanguage *)other;

+ (EduStanfordNlpInternationalLanguage *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(EduStanfordNlpInternationalLanguage)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT EduStanfordNlpInternationalLanguage *EduStanfordNlpInternationalLanguage_values_[];

inline EduStanfordNlpInternationalLanguage *EduStanfordNlpInternationalLanguage_get_Any();
J2OBJC_ENUM_CONSTANT(EduStanfordNlpInternationalLanguage, Any)

inline EduStanfordNlpInternationalLanguage *EduStanfordNlpInternationalLanguage_get_Arabic();
J2OBJC_ENUM_CONSTANT(EduStanfordNlpInternationalLanguage, Arabic)

inline EduStanfordNlpInternationalLanguage *EduStanfordNlpInternationalLanguage_get_Chinese();
J2OBJC_ENUM_CONSTANT(EduStanfordNlpInternationalLanguage, Chinese)

inline EduStanfordNlpInternationalLanguage *EduStanfordNlpInternationalLanguage_get_English();
J2OBJC_ENUM_CONSTANT(EduStanfordNlpInternationalLanguage, English)

inline EduStanfordNlpInternationalLanguage *EduStanfordNlpInternationalLanguage_get_German();
J2OBJC_ENUM_CONSTANT(EduStanfordNlpInternationalLanguage, German)

inline EduStanfordNlpInternationalLanguage *EduStanfordNlpInternationalLanguage_get_French();
J2OBJC_ENUM_CONSTANT(EduStanfordNlpInternationalLanguage, French)

inline EduStanfordNlpInternationalLanguage *EduStanfordNlpInternationalLanguage_get_Hebrew();
J2OBJC_ENUM_CONSTANT(EduStanfordNlpInternationalLanguage, Hebrew)

inline EduStanfordNlpInternationalLanguage *EduStanfordNlpInternationalLanguage_get_Spanish();
J2OBJC_ENUM_CONSTANT(EduStanfordNlpInternationalLanguage, Spanish)

inline EduStanfordNlpInternationalLanguage *EduStanfordNlpInternationalLanguage_get_UniversalEnglish();
J2OBJC_ENUM_CONSTANT(EduStanfordNlpInternationalLanguage, UniversalEnglish)

inline EduStanfordNlpInternationalLanguage *EduStanfordNlpInternationalLanguage_get_Unknown();
J2OBJC_ENUM_CONSTANT(EduStanfordNlpInternationalLanguage, Unknown)

J2OBJC_FIELD_SETTER(EduStanfordNlpInternationalLanguage, params_, id<EduStanfordNlpParserLexparserTreebankLangParserParams>)

inline NSString *EduStanfordNlpInternationalLanguage_get_langList();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EduStanfordNlpInternationalLanguage_langList;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpInternationalLanguage, langList, NSString *)

FOUNDATION_EXPORT IOSObjectArray *EduStanfordNlpInternationalLanguage_values();

FOUNDATION_EXPORT EduStanfordNlpInternationalLanguage *EduStanfordNlpInternationalLanguage_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT EduStanfordNlpInternationalLanguage *EduStanfordNlpInternationalLanguage_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpInternationalLanguage)

#endif

#pragma pop_macro("INCLUDE_ALL_EduStanfordNlpInternationalLanguage")
