//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/ling/tokensregex/parser/SimpleCharStream.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduStanfordNlpLingTokensregexParserSimpleCharStream")
#ifdef RESTRICT_EduStanfordNlpLingTokensregexParserSimpleCharStream
#define INCLUDE_ALL_EduStanfordNlpLingTokensregexParserSimpleCharStream 0
#else
#define INCLUDE_ALL_EduStanfordNlpLingTokensregexParserSimpleCharStream 1
#endif
#undef RESTRICT_EduStanfordNlpLingTokensregexParserSimpleCharStream

#if !defined (EduStanfordNlpLingTokensregexParserSimpleCharStream_) && (INCLUDE_ALL_EduStanfordNlpLingTokensregexParserSimpleCharStream || defined(INCLUDE_EduStanfordNlpLingTokensregexParserSimpleCharStream))
#define EduStanfordNlpLingTokensregexParserSimpleCharStream_

@class IOSCharArray;
@class IOSIntArray;
@class JavaIoInputStream;
@class JavaIoReader;

@interface EduStanfordNlpLingTokensregexParserSimpleCharStream : NSObject {
 @public
  jint bufsize_;
  jint available_;
  jint tokenBegin_;
  jint bufpos_;
  IOSIntArray *bufline_;
  IOSIntArray *bufcolumn_;
  jint column_;
  jint line_;
  jboolean prevCharIsCR_;
  jboolean prevCharIsLF_;
  JavaIoReader *inputStream_;
  IOSCharArray *buffer_;
  jint maxNextCharInd_;
  jint inBuf_;
  jint tabSize_;
}

#pragma mark Public

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)dstream;

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)dstream
                                  withInt:(jint)startline
                                  withInt:(jint)startcolumn;

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)dstream
                                  withInt:(jint)startline
                                  withInt:(jint)startcolumn
                                  withInt:(jint)buffersize;

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)dstream
                             withNSString:(NSString *)encoding;

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)dstream
                             withNSString:(NSString *)encoding
                                  withInt:(jint)startline
                                  withInt:(jint)startcolumn;

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)dstream
                             withNSString:(NSString *)encoding
                                  withInt:(jint)startline
                                  withInt:(jint)startcolumn
                                  withInt:(jint)buffersize;

- (instancetype)initWithJavaIoReader:(JavaIoReader *)dstream;

- (instancetype)initWithJavaIoReader:(JavaIoReader *)dstream
                             withInt:(jint)startline
                             withInt:(jint)startcolumn;

- (instancetype)initWithJavaIoReader:(JavaIoReader *)dstream
                             withInt:(jint)startline
                             withInt:(jint)startcolumn
                             withInt:(jint)buffersize;

- (void)adjustBeginLineColumnWithInt:(jint)newLine
                             withInt:(jint)newCol;

- (void)backupWithInt:(jint)amount;

- (jchar)BeginToken;

- (void)Done;

- (jint)getBeginColumn;

- (jint)getBeginLine;

- (jint)getColumn;

- (jint)getEndColumn;

- (jint)getEndLine;

- (NSString *)GetImage;

- (jint)getLine;

- (IOSCharArray *)GetSuffixWithInt:(jint)len;

- (jchar)readChar;

- (void)ReInitWithJavaIoInputStream:(JavaIoInputStream *)dstream;

- (void)ReInitWithJavaIoInputStream:(JavaIoInputStream *)dstream
                            withInt:(jint)startline
                            withInt:(jint)startcolumn;

- (void)ReInitWithJavaIoInputStream:(JavaIoInputStream *)dstream
                            withInt:(jint)startline
                            withInt:(jint)startcolumn
                            withInt:(jint)buffersize;

- (void)ReInitWithJavaIoInputStream:(JavaIoInputStream *)dstream
                       withNSString:(NSString *)encoding;

- (void)ReInitWithJavaIoInputStream:(JavaIoInputStream *)dstream
                       withNSString:(NSString *)encoding
                            withInt:(jint)startline
                            withInt:(jint)startcolumn;

- (void)ReInitWithJavaIoInputStream:(JavaIoInputStream *)dstream
                       withNSString:(NSString *)encoding
                            withInt:(jint)startline
                            withInt:(jint)startcolumn
                            withInt:(jint)buffersize;

- (void)ReInitWithJavaIoReader:(JavaIoReader *)dstream;

- (void)ReInitWithJavaIoReader:(JavaIoReader *)dstream
                       withInt:(jint)startline
                       withInt:(jint)startcolumn;

- (void)ReInitWithJavaIoReader:(JavaIoReader *)dstream
                       withInt:(jint)startline
                       withInt:(jint)startcolumn
                       withInt:(jint)buffersize;

#pragma mark Protected

- (void)ExpandBuffWithBoolean:(jboolean)wrapAround;

- (void)FillBuff;

- (jint)getTabSizeWithInt:(jint)i;

- (void)setTabSizeWithInt:(jint)i;

- (void)UpdateLineColumnWithChar:(jchar)c;

@end

J2OBJC_EMPTY_STATIC_INIT(EduStanfordNlpLingTokensregexParserSimpleCharStream)

J2OBJC_FIELD_SETTER(EduStanfordNlpLingTokensregexParserSimpleCharStream, bufline_, IOSIntArray *)
J2OBJC_FIELD_SETTER(EduStanfordNlpLingTokensregexParserSimpleCharStream, bufcolumn_, IOSIntArray *)
J2OBJC_FIELD_SETTER(EduStanfordNlpLingTokensregexParserSimpleCharStream, inputStream_, JavaIoReader *)
J2OBJC_FIELD_SETTER(EduStanfordNlpLingTokensregexParserSimpleCharStream, buffer_, IOSCharArray *)

inline jboolean EduStanfordNlpLingTokensregexParserSimpleCharStream_get_staticFlag();
#define EduStanfordNlpLingTokensregexParserSimpleCharStream_staticFlag false
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpLingTokensregexParserSimpleCharStream, staticFlag, jboolean)

FOUNDATION_EXPORT void EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoReader_withInt_withInt_withInt_(EduStanfordNlpLingTokensregexParserSimpleCharStream *self, JavaIoReader *dstream, jint startline, jint startcolumn, jint buffersize);

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *new_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoReader_withInt_withInt_withInt_(JavaIoReader *dstream, jint startline, jint startcolumn, jint buffersize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *create_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoReader_withInt_withInt_withInt_(JavaIoReader *dstream, jint startline, jint startcolumn, jint buffersize);

FOUNDATION_EXPORT void EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoReader_withInt_withInt_(EduStanfordNlpLingTokensregexParserSimpleCharStream *self, JavaIoReader *dstream, jint startline, jint startcolumn);

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *new_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoReader_withInt_withInt_(JavaIoReader *dstream, jint startline, jint startcolumn) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *create_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoReader_withInt_withInt_(JavaIoReader *dstream, jint startline, jint startcolumn);

FOUNDATION_EXPORT void EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoReader_(EduStanfordNlpLingTokensregexParserSimpleCharStream *self, JavaIoReader *dstream);

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *new_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoReader_(JavaIoReader *dstream) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *create_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoReader_(JavaIoReader *dstream);

FOUNDATION_EXPORT void EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_withNSString_withInt_withInt_withInt_(EduStanfordNlpLingTokensregexParserSimpleCharStream *self, JavaIoInputStream *dstream, NSString *encoding, jint startline, jint startcolumn, jint buffersize);

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *new_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_withNSString_withInt_withInt_withInt_(JavaIoInputStream *dstream, NSString *encoding, jint startline, jint startcolumn, jint buffersize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *create_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_withNSString_withInt_withInt_withInt_(JavaIoInputStream *dstream, NSString *encoding, jint startline, jint startcolumn, jint buffersize);

FOUNDATION_EXPORT void EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_withInt_withInt_withInt_(EduStanfordNlpLingTokensregexParserSimpleCharStream *self, JavaIoInputStream *dstream, jint startline, jint startcolumn, jint buffersize);

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *new_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_withInt_withInt_withInt_(JavaIoInputStream *dstream, jint startline, jint startcolumn, jint buffersize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *create_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_withInt_withInt_withInt_(JavaIoInputStream *dstream, jint startline, jint startcolumn, jint buffersize);

FOUNDATION_EXPORT void EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_withNSString_withInt_withInt_(EduStanfordNlpLingTokensregexParserSimpleCharStream *self, JavaIoInputStream *dstream, NSString *encoding, jint startline, jint startcolumn);

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *new_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_withNSString_withInt_withInt_(JavaIoInputStream *dstream, NSString *encoding, jint startline, jint startcolumn) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *create_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_withNSString_withInt_withInt_(JavaIoInputStream *dstream, NSString *encoding, jint startline, jint startcolumn);

FOUNDATION_EXPORT void EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_withInt_withInt_(EduStanfordNlpLingTokensregexParserSimpleCharStream *self, JavaIoInputStream *dstream, jint startline, jint startcolumn);

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *new_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_withInt_withInt_(JavaIoInputStream *dstream, jint startline, jint startcolumn) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *create_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_withInt_withInt_(JavaIoInputStream *dstream, jint startline, jint startcolumn);

FOUNDATION_EXPORT void EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_withNSString_(EduStanfordNlpLingTokensregexParserSimpleCharStream *self, JavaIoInputStream *dstream, NSString *encoding);

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *new_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_withNSString_(JavaIoInputStream *dstream, NSString *encoding) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *create_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_withNSString_(JavaIoInputStream *dstream, NSString *encoding);

FOUNDATION_EXPORT void EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_(EduStanfordNlpLingTokensregexParserSimpleCharStream *self, JavaIoInputStream *dstream);

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *new_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_(JavaIoInputStream *dstream) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpLingTokensregexParserSimpleCharStream *create_EduStanfordNlpLingTokensregexParserSimpleCharStream_initWithJavaIoInputStream_(JavaIoInputStream *dstream);

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpLingTokensregexParserSimpleCharStream)

#endif

#pragma pop_macro("INCLUDE_ALL_EduStanfordNlpLingTokensregexParserSimpleCharStream")
