//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/process/WordShapeClassifier.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduStanfordNlpProcessWordShapeClassifier")
#ifdef RESTRICT_EduStanfordNlpProcessWordShapeClassifier
#define INCLUDE_ALL_EduStanfordNlpProcessWordShapeClassifier 0
#else
#define INCLUDE_ALL_EduStanfordNlpProcessWordShapeClassifier 1
#endif
#undef RESTRICT_EduStanfordNlpProcessWordShapeClassifier

#if !defined (EduStanfordNlpProcessWordShapeClassifier_) && (INCLUDE_ALL_EduStanfordNlpProcessWordShapeClassifier || defined(INCLUDE_EduStanfordNlpProcessWordShapeClassifier))
#define EduStanfordNlpProcessWordShapeClassifier_

@class IOSObjectArray;
@protocol JavaUtilCollection;

@interface EduStanfordNlpProcessWordShapeClassifier : NSObject

#pragma mark Public

+ (jint)lookupShaperWithNSString:(NSString *)name;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

+ (NSString *)wordShapeWithNSString:(NSString *)inStr
                            withInt:(jint)wordShaper;

+ (NSString *)wordShapeWithNSString:(NSString *)inStr
                            withInt:(jint)wordShaper
             withJavaUtilCollection:(id<JavaUtilCollection>)knownLCWords;

+ (NSString *)wordShapeChris4WithNSString:(NSString *)s;

@end

J2OBJC_STATIC_INIT(EduStanfordNlpProcessWordShapeClassifier)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_NOWORDSHAPE();
#define EduStanfordNlpProcessWordShapeClassifier_NOWORDSHAPE -1
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, NOWORDSHAPE, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPEDAN1();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPEDAN1 0
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPEDAN1, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPECHRIS1();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPECHRIS1 1
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPECHRIS1, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPEDAN2();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPEDAN2 2
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPEDAN2, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPEDAN2USELC();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPEDAN2USELC 3
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPEDAN2USELC, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPEDAN2BIO();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPEDAN2BIO 4
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPEDAN2BIO, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPEDAN2BIOUSELC();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPEDAN2BIOUSELC 5
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPEDAN2BIOUSELC, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPEJENNY1();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPEJENNY1 6
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPEJENNY1, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPEJENNY1USELC();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPEJENNY1USELC 7
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPEJENNY1USELC, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPECHRIS2();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPECHRIS2 8
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPECHRIS2, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPECHRIS2USELC();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPECHRIS2USELC 9
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPECHRIS2USELC, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPECHRIS3();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPECHRIS3 10
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPECHRIS3, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPECHRIS3USELC();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPECHRIS3USELC 11
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPECHRIS3USELC, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPECHRIS4();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPECHRIS4 12
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPECHRIS4, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPEDIGITS();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPEDIGITS 13
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPEDIGITS, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPECHINESE();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPECHINESE 14
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPECHINESE, jint)

inline jint EduStanfordNlpProcessWordShapeClassifier_get_WORDSHAPECLUSTER1();
#define EduStanfordNlpProcessWordShapeClassifier_WORDSHAPECLUSTER1 15
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpProcessWordShapeClassifier, WORDSHAPECLUSTER1, jint)

FOUNDATION_EXPORT jint EduStanfordNlpProcessWordShapeClassifier_lookupShaperWithNSString_(NSString *name);

FOUNDATION_EXPORT NSString *EduStanfordNlpProcessWordShapeClassifier_wordShapeWithNSString_withInt_(NSString *inStr, jint wordShaper);

FOUNDATION_EXPORT NSString *EduStanfordNlpProcessWordShapeClassifier_wordShapeWithNSString_withInt_withJavaUtilCollection_(NSString *inStr, jint wordShaper, id<JavaUtilCollection> knownLCWords);

FOUNDATION_EXPORT NSString *EduStanfordNlpProcessWordShapeClassifier_wordShapeChris4WithNSString_(NSString *s);

FOUNDATION_EXPORT void EduStanfordNlpProcessWordShapeClassifier_mainWithNSStringArray_(IOSObjectArray *args);

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpProcessWordShapeClassifier)

#endif

#pragma pop_macro("INCLUDE_ALL_EduStanfordNlpProcessWordShapeClassifier")
