//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/tagger/maxent/CtbDict.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "edu/stanford/nlp/tagger/maxent/CtbDict.h"
#include "edu/stanford/nlp/util/Generics.h"
#include "java/io/BufferedReader.h"
#include "java/io/FileInputStream.h"
#include "java/io/IOException.h"
#include "java/io/InputStreamReader.h"
#include "java/lang/RuntimeException.h"
#include "java/util/Map.h"
#include "java/util/Set.h"

@interface EduStanfordNlpTaggerMaxentCtbDict ()

+ (EduStanfordNlpTaggerMaxentCtbDict *)getInstance;

- (instancetype)init;

- (void)readCtbDictWithNSString:(NSString *)filename;

- (id<JavaUtilSet>)getpreWithNSString:(NSString *)a;

- (id<JavaUtilSet>)getsufWithNSString:(NSString *)a;

@end

inline NSString *EduStanfordNlpTaggerMaxentCtbDict_get_defaultFilename();
static NSString *EduStanfordNlpTaggerMaxentCtbDict_defaultFilename = @"ctb_dict.txt";
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTaggerMaxentCtbDict, defaultFilename, NSString *)

inline EduStanfordNlpTaggerMaxentCtbDict *EduStanfordNlpTaggerMaxentCtbDict_get_ctbDictSingleton();
inline EduStanfordNlpTaggerMaxentCtbDict *EduStanfordNlpTaggerMaxentCtbDict_set_ctbDictSingleton(EduStanfordNlpTaggerMaxentCtbDict *value);
static EduStanfordNlpTaggerMaxentCtbDict *EduStanfordNlpTaggerMaxentCtbDict_ctbDictSingleton;
J2OBJC_STATIC_FIELD_OBJ(EduStanfordNlpTaggerMaxentCtbDict, ctbDictSingleton, EduStanfordNlpTaggerMaxentCtbDict *)

__attribute__((unused)) static EduStanfordNlpTaggerMaxentCtbDict *EduStanfordNlpTaggerMaxentCtbDict_getInstance();

__attribute__((unused)) static void EduStanfordNlpTaggerMaxentCtbDict_init(EduStanfordNlpTaggerMaxentCtbDict *self);

__attribute__((unused)) static EduStanfordNlpTaggerMaxentCtbDict *new_EduStanfordNlpTaggerMaxentCtbDict_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static EduStanfordNlpTaggerMaxentCtbDict *create_EduStanfordNlpTaggerMaxentCtbDict_init();

__attribute__((unused)) static void EduStanfordNlpTaggerMaxentCtbDict_readCtbDictWithNSString_(EduStanfordNlpTaggerMaxentCtbDict *self, NSString *filename);

__attribute__((unused)) static id<JavaUtilSet> EduStanfordNlpTaggerMaxentCtbDict_getpreWithNSString_(EduStanfordNlpTaggerMaxentCtbDict *self, NSString *a);

__attribute__((unused)) static id<JavaUtilSet> EduStanfordNlpTaggerMaxentCtbDict_getsufWithNSString_(EduStanfordNlpTaggerMaxentCtbDict *self, NSString *a);

@implementation EduStanfordNlpTaggerMaxentCtbDict

+ (EduStanfordNlpTaggerMaxentCtbDict *)getInstance {
  return EduStanfordNlpTaggerMaxentCtbDict_getInstance();
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  EduStanfordNlpTaggerMaxentCtbDict_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)readCtbDictWithNSString:(NSString *)filename {
  EduStanfordNlpTaggerMaxentCtbDict_readCtbDictWithNSString_(self, filename);
}

+ (NSString *)getTagPreWithNSString:(NSString *)a1
                       withNSString:(NSString *)a2 {
  return EduStanfordNlpTaggerMaxentCtbDict_getTagPreWithNSString_withNSString_(a1, a2);
}

+ (NSString *)getTagSufWithNSString:(NSString *)a1
                       withNSString:(NSString *)a2 {
  return EduStanfordNlpTaggerMaxentCtbDict_getTagSufWithNSString_withNSString_(a1, a2);
}

- (id<JavaUtilSet>)getpreWithNSString:(NSString *)a {
  return EduStanfordNlpTaggerMaxentCtbDict_getpreWithNSString_(self, a);
}

- (id<JavaUtilSet>)getsufWithNSString:(NSString *)a {
  return EduStanfordNlpTaggerMaxentCtbDict_getsufWithNSString_(self, a);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LEduStanfordNlpTaggerMaxentCtbDict;", 0x2a, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 0, 1, 2, -1, -1, -1 },
    { NULL, "LNSString;", 0xc, 3, 4, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0xc, 5, 4, -1, -1, -1, -1 },
    { NULL, "LJavaUtilSet;", 0x2, 6, 1, -1, 7, -1, -1 },
    { NULL, "LJavaUtilSet;", 0x2, 8, 1, -1, 7, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getInstance);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(readCtbDictWithNSString:);
  methods[3].selector = @selector(getTagPreWithNSString:withNSString:);
  methods[4].selector = @selector(getTagSufWithNSString:withNSString:);
  methods[5].selector = @selector(getpreWithNSString:);
  methods[6].selector = @selector(getsufWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "defaultFilename", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 9, -1, -1 },
    { "ctbDictSingleton", "LEduStanfordNlpTaggerMaxentCtbDict;", .constantValue.asLong = 0, 0xa, -1, 10, -1, -1 },
    { "ctb_pre_dict_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x1, -1, -1, 11, -1 },
    { "ctb_suf_dict_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x1, -1, -1, 11, -1 },
  };
  static const void *ptrTable[] = { "readCtbDict", "LNSString;", "LJavaIoIOException;", "getTagPre", "LNSString;LNSString;", "getTagSuf", "getpre", "(Ljava/lang/String;)Ljava/util/Set<Ljava/lang/String;>;", "getsuf", &EduStanfordNlpTaggerMaxentCtbDict_defaultFilename, &EduStanfordNlpTaggerMaxentCtbDict_ctbDictSingleton, "Ljava/util/Map<Ljava/lang/String;Ljava/util/Set<Ljava/lang/String;>;>;" };
  static const J2ObjcClassInfo _EduStanfordNlpTaggerMaxentCtbDict = { "CtbDict", "edu.stanford.nlp.tagger.maxent", ptrTable, methods, fields, 7, 0x1, 7, 4, -1, -1, -1, -1, -1 };
  return &_EduStanfordNlpTaggerMaxentCtbDict;
}

@end

EduStanfordNlpTaggerMaxentCtbDict *EduStanfordNlpTaggerMaxentCtbDict_getInstance() {
  EduStanfordNlpTaggerMaxentCtbDict_initialize();
  @synchronized(EduStanfordNlpTaggerMaxentCtbDict_class_()) {
    if (EduStanfordNlpTaggerMaxentCtbDict_ctbDictSingleton == nil) {
      EduStanfordNlpTaggerMaxentCtbDict_ctbDictSingleton = new_EduStanfordNlpTaggerMaxentCtbDict_init();
    }
    return EduStanfordNlpTaggerMaxentCtbDict_ctbDictSingleton;
  }
}

void EduStanfordNlpTaggerMaxentCtbDict_init(EduStanfordNlpTaggerMaxentCtbDict *self) {
  NSObject_init(self);
  @try {
    EduStanfordNlpTaggerMaxentCtbDict_readCtbDictWithNSString_(self, JreStrcat("$$", @"/u/nlp/data/pos-tagger/dictionary/", EduStanfordNlpTaggerMaxentCtbDict_defaultFilename));
  }
  @catch (JavaIoIOException *e) {
    @throw new_JavaLangRuntimeException_initWithNSString_(JreStrcat("$$", @"can't open file: ", [((JavaIoIOException *) nil_chk(e)) getMessage]));
  }
}

EduStanfordNlpTaggerMaxentCtbDict *new_EduStanfordNlpTaggerMaxentCtbDict_init() {
  J2OBJC_NEW_IMPL(EduStanfordNlpTaggerMaxentCtbDict, init)
}

EduStanfordNlpTaggerMaxentCtbDict *create_EduStanfordNlpTaggerMaxentCtbDict_init() {
  J2OBJC_CREATE_IMPL(EduStanfordNlpTaggerMaxentCtbDict, init)
}

void EduStanfordNlpTaggerMaxentCtbDict_readCtbDictWithNSString_(EduStanfordNlpTaggerMaxentCtbDict *self, NSString *filename) {
  JavaIoBufferedReader *ctbDetectorReader = new_JavaIoBufferedReader_initWithJavaIoReader_(new_JavaIoInputStreamReader_initWithJavaIoInputStream_withNSString_(new_JavaIoFileInputStream_initWithNSString_(filename), @"GB18030"));
  NSString *ctbDetectorLine;
  self->ctb_pre_dict_ = EduStanfordNlpUtilGenerics_newHashMap();
  self->ctb_suf_dict_ = EduStanfordNlpUtilGenerics_newHashMap();
  while ((ctbDetectorLine = [ctbDetectorReader readLine]) != nil) {
    IOSObjectArray *fields = [((NSString *) nil_chk(ctbDetectorLine)) split:@"\t"];
    NSString *tag = IOSObjectArray_Get(nil_chk(fields), 0);
    id<JavaUtilSet> pres = [((id<JavaUtilMap>) nil_chk(self->ctb_pre_dict_)) getWithId:tag];
    id<JavaUtilSet> sufs = [((id<JavaUtilMap>) nil_chk(self->ctb_suf_dict_)) getWithId:tag];
    if (pres == nil) {
      pres = EduStanfordNlpUtilGenerics_newHashSet();
      (void) [((id<JavaUtilMap>) nil_chk(self->ctb_pre_dict_)) putWithId:tag withId:pres];
    }
    [((id<JavaUtilSet>) nil_chk(pres)) addWithId:IOSObjectArray_Get(fields, 1)];
    if (sufs == nil) {
      sufs = EduStanfordNlpUtilGenerics_newHashSet();
      (void) [((id<JavaUtilMap>) nil_chk(self->ctb_suf_dict_)) putWithId:tag withId:sufs];
    }
    [((id<JavaUtilSet>) nil_chk(sufs)) addWithId:IOSObjectArray_Get(fields, 2)];
  }
}

NSString *EduStanfordNlpTaggerMaxentCtbDict_getTagPreWithNSString_withNSString_(NSString *a1, NSString *a2) {
  EduStanfordNlpTaggerMaxentCtbDict_initialize();
  EduStanfordNlpTaggerMaxentCtbDict *dict = EduStanfordNlpTaggerMaxentCtbDict_getInstance();
  if (EduStanfordNlpTaggerMaxentCtbDict_getpreWithNSString_(nil_chk(dict), a1) == nil) return @"0";
  if ([((id<JavaUtilSet>) nil_chk(EduStanfordNlpTaggerMaxentCtbDict_getpreWithNSString_(dict, a1))) containsWithId:a2]) return @"1";
  return @"0";
}

NSString *EduStanfordNlpTaggerMaxentCtbDict_getTagSufWithNSString_withNSString_(NSString *a1, NSString *a2) {
  EduStanfordNlpTaggerMaxentCtbDict_initialize();
  EduStanfordNlpTaggerMaxentCtbDict *dict = EduStanfordNlpTaggerMaxentCtbDict_getInstance();
  if (EduStanfordNlpTaggerMaxentCtbDict_getsufWithNSString_(nil_chk(dict), a1) == nil) return @"0";
  if ([((id<JavaUtilSet>) nil_chk(EduStanfordNlpTaggerMaxentCtbDict_getsufWithNSString_(dict, a1))) containsWithId:a2]) return @"1";
  return @"0";
}

id<JavaUtilSet> EduStanfordNlpTaggerMaxentCtbDict_getpreWithNSString_(EduStanfordNlpTaggerMaxentCtbDict *self, NSString *a) {
  return [((id<JavaUtilMap>) nil_chk(self->ctb_pre_dict_)) getWithId:a];
}

id<JavaUtilSet> EduStanfordNlpTaggerMaxentCtbDict_getsufWithNSString_(EduStanfordNlpTaggerMaxentCtbDict *self, NSString *a) {
  return [((id<JavaUtilMap>) nil_chk(self->ctb_suf_dict_)) getWithId:a];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduStanfordNlpTaggerMaxentCtbDict)
