//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/tagger/maxent/ExtractorWordShapeConjunction.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction")
#ifdef RESTRICT_EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction
#define INCLUDE_ALL_EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction 0
#else
#define INCLUDE_ALL_EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction 1
#endif
#undef RESTRICT_EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction

#if !defined (EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction_) && (INCLUDE_ALL_EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction || defined(INCLUDE_EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction))
#define EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction_

#define RESTRICT_EduStanfordNlpTaggerMaxentExtractor 1
#define INCLUDE_EduStanfordNlpTaggerMaxentExtractor 1
#include "edu/stanford/nlp/tagger/maxent/Extractor.h"

@class EduStanfordNlpTaggerMaxentHistory;
@class EduStanfordNlpTaggerMaxentPairsHolder;

@interface EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction : EduStanfordNlpTaggerMaxentExtractor

#pragma mark Public

- (jboolean)isDynamic;

- (jboolean)isLocal;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype)initWithInt:(jint)left
                    withInt:(jint)right
               withNSString:(NSString *)wsc;

- (NSString *)extractWithEduStanfordNlpTaggerMaxentHistory:(EduStanfordNlpTaggerMaxentHistory *)h
                 withEduStanfordNlpTaggerMaxentPairsHolder:(EduStanfordNlpTaggerMaxentPairsHolder *)pH;

@end

J2OBJC_EMPTY_STATIC_INIT(EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction)

FOUNDATION_EXPORT void EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction_initWithInt_withInt_withNSString_(EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction *self, jint left, jint right, NSString *wsc);

FOUNDATION_EXPORT EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction *new_EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction_initWithInt_withInt_withNSString_(jint left, jint right, NSString *wsc) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction *create_EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction_initWithInt_withInt_withNSString_(jint left, jint right, NSString *wsc);

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction)

#endif

#pragma pop_macro("INCLUDE_ALL_EduStanfordNlpTaggerMaxentExtractorWordShapeConjunction")
