//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/util/logging/PrettyLogger.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduStanfordNlpUtilLoggingPrettyLogger")
#ifdef RESTRICT_EduStanfordNlpUtilLoggingPrettyLogger
#define INCLUDE_ALL_EduStanfordNlpUtilLoggingPrettyLogger 0
#else
#define INCLUDE_ALL_EduStanfordNlpUtilLoggingPrettyLogger 1
#endif
#undef RESTRICT_EduStanfordNlpUtilLoggingPrettyLogger

#if !defined (EduStanfordNlpUtilLoggingPrettyLogger_) && (INCLUDE_ALL_EduStanfordNlpUtilLoggingPrettyLogger || defined(INCLUDE_EduStanfordNlpUtilLoggingPrettyLogger))
#define EduStanfordNlpUtilLoggingPrettyLogger_

@class EduStanfordNlpUtilLoggingRedwood_RedwoodChannels;

@interface EduStanfordNlpUtilLoggingPrettyLogger : NSObject

#pragma mark Public

+ (jboolean)dispatchableWithId:(id)obj;

+ (void)logWithId:(id)obj;

+ (void)logWithEduStanfordNlpUtilLoggingRedwood_RedwoodChannels:(EduStanfordNlpUtilLoggingRedwood_RedwoodChannels *)channels
                                                         withId:(id)obj;

+ (void)logWithEduStanfordNlpUtilLoggingRedwood_RedwoodChannels:(EduStanfordNlpUtilLoggingRedwood_RedwoodChannels *)channels
                                                   withNSString:(NSString *)description_
                                                         withId:(id)obj;

+ (void)logWithNSString:(NSString *)description_
                 withId:(id)obj;

@end

J2OBJC_STATIC_INIT(EduStanfordNlpUtilLoggingPrettyLogger)

FOUNDATION_EXPORT void EduStanfordNlpUtilLoggingPrettyLogger_logWithId_(id obj);

FOUNDATION_EXPORT void EduStanfordNlpUtilLoggingPrettyLogger_logWithNSString_withId_(NSString *description_, id obj);

FOUNDATION_EXPORT void EduStanfordNlpUtilLoggingPrettyLogger_logWithEduStanfordNlpUtilLoggingRedwood_RedwoodChannels_withId_(EduStanfordNlpUtilLoggingRedwood_RedwoodChannels *channels, id obj);

FOUNDATION_EXPORT void EduStanfordNlpUtilLoggingPrettyLogger_logWithEduStanfordNlpUtilLoggingRedwood_RedwoodChannels_withNSString_withId_(EduStanfordNlpUtilLoggingRedwood_RedwoodChannels *channels, NSString *description_, id obj);

FOUNDATION_EXPORT jboolean EduStanfordNlpUtilLoggingPrettyLogger_dispatchableWithId_(id obj);

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpUtilLoggingPrettyLogger)

#endif

#pragma pop_macro("INCLUDE_ALL_EduStanfordNlpUtilLoggingPrettyLogger")
