//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/trees/international/pennchinese/CEDict.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduStanfordNlpTreesInternationalPennchineseCEDict")
#ifdef RESTRICT_EduStanfordNlpTreesInternationalPennchineseCEDict
#define INCLUDE_ALL_EduStanfordNlpTreesInternationalPennchineseCEDict 0
#else
#define INCLUDE_ALL_EduStanfordNlpTreesInternationalPennchineseCEDict 1
#endif
#undef RESTRICT_EduStanfordNlpTreesInternationalPennchineseCEDict

#if !defined (EduStanfordNlpTreesInternationalPennchineseCEDict_) && (INCLUDE_ALL_EduStanfordNlpTreesInternationalPennchineseCEDict || defined(INCLUDE_EduStanfordNlpTreesInternationalPennchineseCEDict))
#define EduStanfordNlpTreesInternationalPennchineseCEDict_

@interface EduStanfordNlpTreesInternationalPennchineseCEDict : NSObject

#pragma mark Public

+ (NSString *)path;

@end

J2OBJC_EMPTY_STATIC_INIT(EduStanfordNlpTreesInternationalPennchineseCEDict)

FOUNDATION_EXPORT NSString *EduStanfordNlpTreesInternationalPennchineseCEDict_path();

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpTreesInternationalPennchineseCEDict)

#endif

#pragma pop_macro("INCLUDE_ALL_EduStanfordNlpTreesInternationalPennchineseCEDict")
