//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/trees/international/pennchinese/CEDict.java
//

#include "J2ObjC_source.h"
#include "edu/stanford/nlp/trees/international/pennchinese/CEDict.h"
#include "java/io/File.h"
#include "java/lang/RuntimeException.h"
#include "java/lang/System.h"

@interface EduStanfordNlpTreesInternationalPennchineseCEDict ()

- (instancetype)init;

@end

inline NSString *EduStanfordNlpTreesInternationalPennchineseCEDict_get_defaultPath();
static NSString *EduStanfordNlpTreesInternationalPennchineseCEDict_defaultPath = @"cedict_ts.u8";
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesInternationalPennchineseCEDict, defaultPath, NSString *)

inline NSString *EduStanfordNlpTreesInternationalPennchineseCEDict_get_defaultPath2();
static NSString *EduStanfordNlpTreesInternationalPennchineseCEDict_defaultPath2 = @"/u/nlp/data/chinese-english-dictionary/cedict_ts.u8";
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesInternationalPennchineseCEDict, defaultPath2, NSString *)

inline NSString *EduStanfordNlpTreesInternationalPennchineseCEDict_get_ENV_VARIABLE();
static NSString *EduStanfordNlpTreesInternationalPennchineseCEDict_ENV_VARIABLE = @"CEDICT";
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesInternationalPennchineseCEDict, ENV_VARIABLE, NSString *)

__attribute__((unused)) static void EduStanfordNlpTreesInternationalPennchineseCEDict_init(EduStanfordNlpTreesInternationalPennchineseCEDict *self);

__attribute__((unused)) static EduStanfordNlpTreesInternationalPennchineseCEDict *new_EduStanfordNlpTreesInternationalPennchineseCEDict_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static EduStanfordNlpTreesInternationalPennchineseCEDict *create_EduStanfordNlpTreesInternationalPennchineseCEDict_init();

@implementation EduStanfordNlpTreesInternationalPennchineseCEDict

+ (NSString *)path {
  return EduStanfordNlpTreesInternationalPennchineseCEDict_path();
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  EduStanfordNlpTreesInternationalPennchineseCEDict_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(path);
  methods[1].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "defaultPath", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 0, -1, -1 },
    { "defaultPath2", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 1, -1, -1 },
    { "ENV_VARIABLE", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 2, -1, -1 },
  };
  static const void *ptrTable[] = { &EduStanfordNlpTreesInternationalPennchineseCEDict_defaultPath, &EduStanfordNlpTreesInternationalPennchineseCEDict_defaultPath2, &EduStanfordNlpTreesInternationalPennchineseCEDict_ENV_VARIABLE };
  static const J2ObjcClassInfo _EduStanfordNlpTreesInternationalPennchineseCEDict = { "CEDict", "edu.stanford.nlp.trees.international.pennchinese", ptrTable, methods, fields, 7, 0x1, 2, 3, -1, -1, -1, -1, -1 };
  return &_EduStanfordNlpTreesInternationalPennchineseCEDict;
}

@end

NSString *EduStanfordNlpTreesInternationalPennchineseCEDict_path() {
  EduStanfordNlpTreesInternationalPennchineseCEDict_initialize();
  JavaIoFile *f = new_JavaIoFile_initWithNSString_(EduStanfordNlpTreesInternationalPennchineseCEDict_defaultPath);
  if ([f canRead]) {
    return EduStanfordNlpTreesInternationalPennchineseCEDict_defaultPath;
  }
  else {
    f = new_JavaIoFile_initWithNSString_(EduStanfordNlpTreesInternationalPennchineseCEDict_defaultPath2);
    if ([f canRead]) {
      return EduStanfordNlpTreesInternationalPennchineseCEDict_defaultPath2;
    }
    else {
      NSString *path = JavaLangSystem_getenvWithNSString_(EduStanfordNlpTreesInternationalPennchineseCEDict_ENV_VARIABLE);
      f = new_JavaIoFile_initWithNSString_(path);
      if (![f canRead]) {
        @throw new_JavaLangRuntimeException_initWithNSString_(@"ChineseEnglishWordMap cannot find dictionary");
      }
      return path;
    }
  }
}

void EduStanfordNlpTreesInternationalPennchineseCEDict_init(EduStanfordNlpTreesInternationalPennchineseCEDict *self) {
  NSObject_init(self);
}

EduStanfordNlpTreesInternationalPennchineseCEDict *new_EduStanfordNlpTreesInternationalPennchineseCEDict_init() {
  J2OBJC_NEW_IMPL(EduStanfordNlpTreesInternationalPennchineseCEDict, init)
}

EduStanfordNlpTreesInternationalPennchineseCEDict *create_EduStanfordNlpTreesInternationalPennchineseCEDict_init() {
  J2OBJC_CREATE_IMPL(EduStanfordNlpTreesInternationalPennchineseCEDict, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduStanfordNlpTreesInternationalPennchineseCEDict)
