//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/trees/EnglishPatterns.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduStanfordNlpTreesEnglishPatterns")
#ifdef RESTRICT_EduStanfordNlpTreesEnglishPatterns
#define INCLUDE_ALL_EduStanfordNlpTreesEnglishPatterns 0
#else
#define INCLUDE_ALL_EduStanfordNlpTreesEnglishPatterns 1
#endif
#undef RESTRICT_EduStanfordNlpTreesEnglishPatterns

#if !defined (EduStanfordNlpTreesEnglishPatterns_) && (INCLUDE_ALL_EduStanfordNlpTreesEnglishPatterns || defined(INCLUDE_EduStanfordNlpTreesEnglishPatterns))
#define EduStanfordNlpTreesEnglishPatterns_

@class IOSObjectArray;
@class JavaUtilRegexPattern;

@interface EduStanfordNlpTreesEnglishPatterns : NSObject

@end

J2OBJC_STATIC_INIT(EduStanfordNlpTreesEnglishPatterns)

inline IOSObjectArray *EduStanfordNlpTreesEnglishPatterns_get_copularVerbs();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSObjectArray *EduStanfordNlpTreesEnglishPatterns_copularVerbs;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, copularVerbs, IOSObjectArray *)

inline IOSObjectArray *EduStanfordNlpTreesEnglishPatterns_get_beGetVerbs();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSObjectArray *EduStanfordNlpTreesEnglishPatterns_beGetVerbs;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, beGetVerbs, IOSObjectArray *)

inline NSString *EduStanfordNlpTreesEnglishPatterns_get_timeWordRegex();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EduStanfordNlpTreesEnglishPatterns_timeWordRegex;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, timeWordRegex, NSString *)

inline NSString *EduStanfordNlpTreesEnglishPatterns_get_timeWordLotRegex();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EduStanfordNlpTreesEnglishPatterns_timeWordLotRegex;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, timeWordLotRegex, NSString *)

inline NSString *EduStanfordNlpTreesEnglishPatterns_get_copularWordRegex();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EduStanfordNlpTreesEnglishPatterns_copularWordRegex;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, copularWordRegex, NSString *)

inline NSString *EduStanfordNlpTreesEnglishPatterns_get_clausalComplementRegex();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EduStanfordNlpTreesEnglishPatterns_clausalComplementRegex;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, clausalComplementRegex, NSString *)

inline NSString *EduStanfordNlpTreesEnglishPatterns_get_passiveAuxWordRegex();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EduStanfordNlpTreesEnglishPatterns_passiveAuxWordRegex;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, passiveAuxWordRegex, NSString *)

inline NSString *EduStanfordNlpTreesEnglishPatterns_get_beAuxiliaryRegex();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EduStanfordNlpTreesEnglishPatterns_beAuxiliaryRegex;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, beAuxiliaryRegex, NSString *)

inline NSString *EduStanfordNlpTreesEnglishPatterns_get_haveRegex();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EduStanfordNlpTreesEnglishPatterns_haveRegex;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, haveRegex, NSString *)

inline NSString *EduStanfordNlpTreesEnglishPatterns_get_selfRegex();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EduStanfordNlpTreesEnglishPatterns_selfRegex;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, selfRegex, NSString *)

inline NSString *EduStanfordNlpTreesEnglishPatterns_get_xcompVerbRegex();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EduStanfordNlpTreesEnglishPatterns_xcompVerbRegex;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, xcompVerbRegex, NSString *)

inline NSString *EduStanfordNlpTreesEnglishPatterns_get_xcompNoObjVerbRegex();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EduStanfordNlpTreesEnglishPatterns_xcompNoObjVerbRegex;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, xcompNoObjVerbRegex, NSString *)

inline NSString *EduStanfordNlpTreesEnglishPatterns_get_ccompVerbRegex();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EduStanfordNlpTreesEnglishPatterns_ccompVerbRegex;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, ccompVerbRegex, NSString *)

inline NSString *EduStanfordNlpTreesEnglishPatterns_get_ccompObjVerbRegex();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EduStanfordNlpTreesEnglishPatterns_ccompObjVerbRegex;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, ccompObjVerbRegex, NSString *)

inline NSString *EduStanfordNlpTreesEnglishPatterns_get_RELATIVIZING_WORD_REGEX();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EduStanfordNlpTreesEnglishPatterns_RELATIVIZING_WORD_REGEX;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, RELATIVIZING_WORD_REGEX, NSString *)

inline JavaUtilRegexPattern *EduStanfordNlpTreesEnglishPatterns_get_RELATIVIZING_WORD_PATTERN();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT JavaUtilRegexPattern *EduStanfordNlpTreesEnglishPatterns_RELATIVIZING_WORD_PATTERN;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, RELATIVIZING_WORD_PATTERN, JavaUtilRegexPattern *)

inline NSString *EduStanfordNlpTreesEnglishPatterns_get_NP_V_S_INF_VERBS_REGEX();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EduStanfordNlpTreesEnglishPatterns_NP_V_S_INF_VERBS_REGEX;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesEnglishPatterns, NP_V_S_INF_VERBS_REGEX, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpTreesEnglishPatterns)

#endif

#pragma pop_macro("INCLUDE_ALL_EduStanfordNlpTreesEnglishPatterns")
