//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/trees/LabeledConstituent.java
//

#include "J2ObjC_source.h"
#include "edu/stanford/nlp/ling/Label.h"
#include "edu/stanford/nlp/ling/LabelFactory.h"
#include "edu/stanford/nlp/ling/StringLabel.h"
#include "edu/stanford/nlp/trees/Constituent.h"
#include "edu/stanford/nlp/trees/ConstituentFactory.h"
#include "edu/stanford/nlp/trees/LabeledConstituent.h"
#include "edu/stanford/nlp/trees/SimpleConstituent.h"

@interface EduStanfordNlpTreesLabeledConstituent () {
 @public
  id<EduStanfordNlpLingLabel> label_;
}

@end

J2OBJC_FIELD_SETTER(EduStanfordNlpTreesLabeledConstituent, label_, id<EduStanfordNlpLingLabel>)

@interface EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory : NSObject < EduStanfordNlpLingLabelFactory >

- (id<EduStanfordNlpLingLabel>)newLabelWithNSString:(NSString *)labelStr OBJC_METHOD_FAMILY_NONE;

- (id<EduStanfordNlpLingLabel>)newLabelWithNSString:(NSString *)labelStr
                                            withInt:(jint)options OBJC_METHOD_FAMILY_NONE;

- (id<EduStanfordNlpLingLabel>)newLabelFromStringWithNSString:(NSString *)labelStr OBJC_METHOD_FAMILY_NONE;

- (id<EduStanfordNlpLingLabel>)newLabelWithEduStanfordNlpLingLabel:(id<EduStanfordNlpLingLabel>)oldLabel OBJC_METHOD_FAMILY_NONE;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory)

__attribute__((unused)) static void EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory_init(EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory *self);

__attribute__((unused)) static EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory *new_EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory *create_EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory_init();

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory)

@interface EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder : NSObject

- (instancetype)init;

@end

J2OBJC_STATIC_INIT(EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder)

inline id<EduStanfordNlpLingLabelFactory> EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder_get_lf();
static id<EduStanfordNlpLingLabelFactory> EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder_lf;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder, lf, id<EduStanfordNlpLingLabelFactory>)

__attribute__((unused)) static void EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder_init(EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder *self);

__attribute__((unused)) static EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder *new_EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder *create_EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder_init();

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder)

@interface EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder : NSObject

- (instancetype)init;

@end

J2OBJC_STATIC_INIT(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder)

inline id<EduStanfordNlpTreesConstituentFactory> EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_get_cf();
static id<EduStanfordNlpTreesConstituentFactory> EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_cf;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder, cf, id<EduStanfordNlpTreesConstituentFactory>)

__attribute__((unused)) static void EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_init(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder *self);

__attribute__((unused)) static EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder *new_EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder *create_EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_init();

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder)

@interface EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory : NSObject < EduStanfordNlpTreesConstituentFactory >

- (EduStanfordNlpTreesConstituent *)newConstituentWithInt:(jint)start
                                                  withInt:(jint)end OBJC_METHOD_FAMILY_NONE;

- (EduStanfordNlpTreesConstituent *)newConstituentWithInt:(jint)start
                                                  withInt:(jint)end
                              withEduStanfordNlpLingLabel:(id<EduStanfordNlpLingLabel>)label
                                               withDouble:(jdouble)score OBJC_METHOD_FAMILY_NONE;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory)

__attribute__((unused)) static void EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory_init(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory *self);

__attribute__((unused)) static EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory *new_EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory *create_EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory_init();

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory)

@implementation EduStanfordNlpTreesLabeledConstituent

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  EduStanfordNlpTreesLabeledConstituent_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithInt:(jint)start
                    withInt:(jint)end {
  EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_(self, start, end);
  return self;
}

- (instancetype)initWithInt:(jint)start
                    withInt:(jint)end
withEduStanfordNlpLingLabel:(id<EduStanfordNlpLingLabel>)label {
  EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_withEduStanfordNlpLingLabel_(self, start, end, label);
  return self;
}

- (instancetype)initWithInt:(jint)start
                    withInt:(jint)end
               withNSString:(NSString *)stringValue {
  EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_withNSString_(self, start, end, stringValue);
  return self;
}

- (id<EduStanfordNlpLingLabel>)label {
  return label_;
}

- (void)setLabelWithEduStanfordNlpLingLabel:(id<EduStanfordNlpLingLabel>)label {
  self->label_ = label;
}

- (void)setFromStringWithNSString:(NSString *)labelStr {
  self->label_ = new_EduStanfordNlpLingStringLabel_initWithNSString_(labelStr);
}

- (id<EduStanfordNlpLingLabelFactory>)labelFactory {
  return JreLoadStatic(EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder, lf);
}

- (id<EduStanfordNlpTreesConstituentFactory>)constituentFactory {
  return JreLoadStatic(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder, cf);
}

+ (id<EduStanfordNlpTreesConstituentFactory>)factory {
  return EduStanfordNlpTreesLabeledConstituent_factory();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpLingLabel;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 5, 6, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpLingLabelFactory;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpTreesConstituentFactory;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpTreesConstituentFactory;", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithInt:withInt:);
  methods[2].selector = @selector(initWithInt:withInt:withEduStanfordNlpLingLabel:);
  methods[3].selector = @selector(initWithInt:withInt:withNSString:);
  methods[4].selector = @selector(label);
  methods[5].selector = @selector(setLabelWithEduStanfordNlpLingLabel:);
  methods[6].selector = @selector(setFromStringWithNSString:);
  methods[7].selector = @selector(labelFactory);
  methods[8].selector = @selector(constituentFactory);
  methods[9].selector = @selector(factory);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "label_", "LEduStanfordNlpLingLabel;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "II", "IILEduStanfordNlpLingLabel;", "IILNSString;", "setLabel", "LEduStanfordNlpLingLabel;", "setFromString", "LNSString;", "LEduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory;LEduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder;LEduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder;" };
  static const J2ObjcClassInfo _EduStanfordNlpTreesLabeledConstituent = { "LabeledConstituent", "edu.stanford.nlp.trees", ptrTable, methods, fields, 7, 0x1, 10, 1, -1, 7, -1, -1, -1 };
  return &_EduStanfordNlpTreesLabeledConstituent;
}

@end

void EduStanfordNlpTreesLabeledConstituent_init(EduStanfordNlpTreesLabeledConstituent *self) {
  EduStanfordNlpTreesSimpleConstituent_init(self);
}

EduStanfordNlpTreesLabeledConstituent *new_EduStanfordNlpTreesLabeledConstituent_init() {
  J2OBJC_NEW_IMPL(EduStanfordNlpTreesLabeledConstituent, init)
}

EduStanfordNlpTreesLabeledConstituent *create_EduStanfordNlpTreesLabeledConstituent_init() {
  J2OBJC_CREATE_IMPL(EduStanfordNlpTreesLabeledConstituent, init)
}

void EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_(EduStanfordNlpTreesLabeledConstituent *self, jint start, jint end) {
  EduStanfordNlpTreesSimpleConstituent_initWithInt_withInt_(self, start, end);
}

EduStanfordNlpTreesLabeledConstituent *new_EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_(jint start, jint end) {
  J2OBJC_NEW_IMPL(EduStanfordNlpTreesLabeledConstituent, initWithInt_withInt_, start, end)
}

EduStanfordNlpTreesLabeledConstituent *create_EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_(jint start, jint end) {
  J2OBJC_CREATE_IMPL(EduStanfordNlpTreesLabeledConstituent, initWithInt_withInt_, start, end)
}

void EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_withEduStanfordNlpLingLabel_(EduStanfordNlpTreesLabeledConstituent *self, jint start, jint end, id<EduStanfordNlpLingLabel> label) {
  EduStanfordNlpTreesSimpleConstituent_initWithInt_withInt_(self, start, end);
  self->label_ = label;
}

EduStanfordNlpTreesLabeledConstituent *new_EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_withEduStanfordNlpLingLabel_(jint start, jint end, id<EduStanfordNlpLingLabel> label) {
  J2OBJC_NEW_IMPL(EduStanfordNlpTreesLabeledConstituent, initWithInt_withInt_withEduStanfordNlpLingLabel_, start, end, label)
}

EduStanfordNlpTreesLabeledConstituent *create_EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_withEduStanfordNlpLingLabel_(jint start, jint end, id<EduStanfordNlpLingLabel> label) {
  J2OBJC_CREATE_IMPL(EduStanfordNlpTreesLabeledConstituent, initWithInt_withInt_withEduStanfordNlpLingLabel_, start, end, label)
}

void EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_withNSString_(EduStanfordNlpTreesLabeledConstituent *self, jint start, jint end, NSString *stringValue) {
  EduStanfordNlpTreesSimpleConstituent_initWithInt_withInt_(self, start, end);
  self->label_ = new_EduStanfordNlpLingStringLabel_initWithNSString_(stringValue);
}

EduStanfordNlpTreesLabeledConstituent *new_EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_withNSString_(jint start, jint end, NSString *stringValue) {
  J2OBJC_NEW_IMPL(EduStanfordNlpTreesLabeledConstituent, initWithInt_withInt_withNSString_, start, end, stringValue)
}

EduStanfordNlpTreesLabeledConstituent *create_EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_withNSString_(jint start, jint end, NSString *stringValue) {
  J2OBJC_CREATE_IMPL(EduStanfordNlpTreesLabeledConstituent, initWithInt_withInt_withNSString_, start, end, stringValue)
}

id<EduStanfordNlpTreesConstituentFactory> EduStanfordNlpTreesLabeledConstituent_factory() {
  EduStanfordNlpTreesLabeledConstituent_initialize();
  return JreLoadStatic(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder, cf);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduStanfordNlpTreesLabeledConstituent)

@implementation EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory

- (id<EduStanfordNlpLingLabel>)newLabelWithNSString:(NSString *)labelStr {
  return new_EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_withEduStanfordNlpLingLabel_(0, 0, new_EduStanfordNlpLingStringLabel_initWithNSString_(labelStr));
}

- (id<EduStanfordNlpLingLabel>)newLabelWithNSString:(NSString *)labelStr
                                            withInt:(jint)options {
  return [self newLabelWithNSString:labelStr];
}

- (id<EduStanfordNlpLingLabel>)newLabelFromStringWithNSString:(NSString *)labelStr {
  return [self newLabelWithNSString:labelStr];
}

- (id<EduStanfordNlpLingLabel>)newLabelWithEduStanfordNlpLingLabel:(id<EduStanfordNlpLingLabel>)oldLabel {
  return new_EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_withEduStanfordNlpLingLabel_(0, 0, oldLabel);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LEduStanfordNlpLingLabel;", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpLingLabel;", 0x1, 0, 2, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpLingLabel;", 0x1, 3, 1, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpLingLabel;", 0x1, 0, 4, -1, -1, -1, -1 },
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(newLabelWithNSString:);
  methods[1].selector = @selector(newLabelWithNSString:withInt:);
  methods[2].selector = @selector(newLabelFromStringWithNSString:);
  methods[3].selector = @selector(newLabelWithEduStanfordNlpLingLabel:);
  methods[4].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "newLabel", "LNSString;", "LNSString;I", "newLabelFromString", "LEduStanfordNlpLingLabel;", "LEduStanfordNlpTreesLabeledConstituent;" };
  static const J2ObjcClassInfo _EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory = { "LabeledConstituentLabelFactory", "edu.stanford.nlp.trees", ptrTable, methods, NULL, 7, 0xa, 5, 0, 5, -1, -1, -1, -1 };
  return &_EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory;
}

@end

void EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory_init(EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory *self) {
  NSObject_init(self);
}

EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory *new_EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory_init() {
  J2OBJC_NEW_IMPL(EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory, init)
}

EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory *create_EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory_init() {
  J2OBJC_CREATE_IMPL(EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory)

J2OBJC_INITIALIZED_DEFN(EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder)

@implementation EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "lf", "LEduStanfordNlpLingLabelFactory;", .constantValue.asLong = 0, 0x18, -1, 0, -1, -1 },
  };
  static const void *ptrTable[] = { &EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder_lf, "LEduStanfordNlpTreesLabeledConstituent;" };
  static const J2ObjcClassInfo _EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder = { "LabelFactoryHolder", "edu.stanford.nlp.trees", ptrTable, methods, fields, 7, 0xa, 1, 1, 1, -1, -1, -1, -1 };
  return &_EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder;
}

+ (void)initialize {
  if (self == [EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder class]) {
    EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder_lf = new_EduStanfordNlpTreesLabeledConstituent_LabeledConstituentLabelFactory_init();
    J2OBJC_SET_INITIALIZED(EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder)
  }
}

@end

void EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder_init(EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder *self) {
  NSObject_init(self);
}

EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder *new_EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder_init() {
  J2OBJC_NEW_IMPL(EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder, init)
}

EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder *create_EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder_init() {
  J2OBJC_CREATE_IMPL(EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduStanfordNlpTreesLabeledConstituent_LabelFactoryHolder)

J2OBJC_INITIALIZED_DEFN(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder)

@implementation EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "cf", "LEduStanfordNlpTreesConstituentFactory;", .constantValue.asLong = 0, 0x18, -1, 0, -1, -1 },
  };
  static const void *ptrTable[] = { &EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_cf, "LEduStanfordNlpTreesLabeledConstituent;", "LEduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory;" };
  static const J2ObjcClassInfo _EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder = { "ConstituentFactoryHolder", "edu.stanford.nlp.trees", ptrTable, methods, fields, 7, 0xa, 1, 1, 1, 2, -1, -1, -1 };
  return &_EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder;
}

+ (void)initialize {
  if (self == [EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder class]) {
    EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_cf = new_EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory_init();
    J2OBJC_SET_INITIALIZED(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder)
  }
}

@end

void EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_init(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder *self) {
  NSObject_init(self);
}

EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder *new_EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_init() {
  J2OBJC_NEW_IMPL(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder, init)
}

EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder *create_EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_init() {
  J2OBJC_CREATE_IMPL(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder)

@implementation EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory

- (EduStanfordNlpTreesConstituent *)newConstituentWithInt:(jint)start
                                                  withInt:(jint)end {
  return new_EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_(start, end);
}

- (EduStanfordNlpTreesConstituent *)newConstituentWithInt:(jint)start
                                                  withInt:(jint)end
                              withEduStanfordNlpLingLabel:(id<EduStanfordNlpLingLabel>)label
                                               withDouble:(jdouble)score {
  return new_EduStanfordNlpTreesLabeledConstituent_initWithInt_withInt_withEduStanfordNlpLingLabel_(start, end, label);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LEduStanfordNlpTreesConstituent;", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpTreesConstituent;", 0x1, 0, 2, -1, -1, -1, -1 },
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(newConstituentWithInt:withInt:);
  methods[1].selector = @selector(newConstituentWithInt:withInt:withEduStanfordNlpLingLabel:withDouble:);
  methods[2].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "newConstituent", "II", "IILEduStanfordNlpLingLabel;D", "LEduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder;" };
  static const J2ObjcClassInfo _EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory = { "LabeledConstituentFactory", "edu.stanford.nlp.trees", ptrTable, methods, NULL, 7, 0xa, 3, 0, 3, -1, -1, -1, -1 };
  return &_EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory;
}

@end

void EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory_init(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory *self) {
  NSObject_init(self);
}

EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory *new_EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory_init() {
  J2OBJC_NEW_IMPL(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory, init)
}

EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory *create_EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory_init() {
  J2OBJC_CREATE_IMPL(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduStanfordNlpTreesLabeledConstituent_ConstituentFactoryHolder_LabeledConstituentFactory)
