//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/trees/international/negra/NegraPennLanguagePack.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack")
#ifdef RESTRICT_EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack
#define INCLUDE_ALL_EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack 0
#else
#define INCLUDE_ALL_EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack 1
#endif
#undef RESTRICT_EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack

#if !defined (EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack_) && (INCLUDE_ALL_EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack || defined(INCLUDE_EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack))
#define EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack_

#define RESTRICT_EduStanfordNlpTreesAbstractTreebankLanguagePack 1
#define INCLUDE_EduStanfordNlpTreesAbstractTreebankLanguagePack 1
#include "edu/stanford/nlp/trees/AbstractTreebankLanguagePack.h"

@class IOSCharArray;
@class IOSObjectArray;
@protocol EduStanfordNlpProcessTokenizerFactory;
@protocol EduStanfordNlpTreesHeadFinder;
@protocol EduStanfordNlpTreesTreeReaderFactory;

@interface EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack : EduStanfordNlpTreesAbstractTreebankLanguagePack

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithBoolean:(jboolean)leaveGF;

- (instancetype)initWithBoolean:(jboolean)leaveGF
                       withChar:(jchar)gfChar;

- (NSString *)basicCategoryWithNSString:(NSString *)category;

- (IOSObjectArray *)evalBIgnoredPunctuationTags;

- (NSString *)getEncoding;

- (id<EduStanfordNlpProcessTokenizerFactory>)getTokenizerFactory;

- (id<EduStanfordNlpTreesHeadFinder>)headFinder;

- (jboolean)isLeaveGF;

- (IOSCharArray *)labelAnnotationIntroducingCharacters;

- (IOSObjectArray *)punctuationTags;

- (IOSObjectArray *)punctuationWords;

- (IOSObjectArray *)sentenceFinalPunctuationTags;

- (IOSObjectArray *)sentenceFinalPunctuationWords;

- (void)setLeaveGFWithBoolean:(jboolean)leaveGF;

- (IOSObjectArray *)startSymbols;

- (NSString *)stripGFWithNSString:(NSString *)category;

- (NSString *)treebankFileExtension;

- (id<EduStanfordNlpTreesTreeReaderFactory>)treeReaderFactory;

- (id<EduStanfordNlpTreesHeadFinder>)typedDependencyHeadFinder;

@end

J2OBJC_STATIC_INIT(EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack)

FOUNDATION_EXPORT void EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack_init(EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack *self);

FOUNDATION_EXPORT EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack *new_EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack *create_EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack_init();

FOUNDATION_EXPORT void EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack_initWithBoolean_(EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack *self, jboolean leaveGF);

FOUNDATION_EXPORT EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack *new_EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack_initWithBoolean_(jboolean leaveGF) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack *create_EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack_initWithBoolean_(jboolean leaveGF);

FOUNDATION_EXPORT void EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack_initWithBoolean_withChar_(EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack *self, jboolean leaveGF, jchar gfChar);

FOUNDATION_EXPORT EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack *new_EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack_initWithBoolean_withChar_(jboolean leaveGF, jchar gfChar) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack *create_EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack_initWithBoolean_withChar_(jboolean leaveGF, jchar gfChar);

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack)

#endif

#pragma pop_macro("INCLUDE_ALL_EduStanfordNlpTreesInternationalNegraNegraPennLanguagePack")
