//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/optimization/CGMinimizer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduStanfordNlpOptimizationCGMinimizer")
#ifdef RESTRICT_EduStanfordNlpOptimizationCGMinimizer
#define INCLUDE_ALL_EduStanfordNlpOptimizationCGMinimizer 0
#else
#define INCLUDE_ALL_EduStanfordNlpOptimizationCGMinimizer 1
#endif
#undef RESTRICT_EduStanfordNlpOptimizationCGMinimizer

#if !defined (EduStanfordNlpOptimizationCGMinimizer_) && (INCLUDE_ALL_EduStanfordNlpOptimizationCGMinimizer || defined(INCLUDE_EduStanfordNlpOptimizationCGMinimizer))
#define EduStanfordNlpOptimizationCGMinimizer_

#define RESTRICT_EduStanfordNlpOptimizationMinimizer 1
#define INCLUDE_EduStanfordNlpOptimizationMinimizer 1
#include "edu/stanford/nlp/optimization/Minimizer.h"

@class EduStanfordNlpUtilCallbackFunction;
@class IOSDoubleArray;
@protocol EduStanfordNlpOptimizationDiffFunction;
@protocol EduStanfordNlpOptimizationFunction;

@interface EduStanfordNlpOptimizationCGMinimizer : NSObject < EduStanfordNlpOptimizationMinimizer >

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithBoolean:(jboolean)silent;

- (instancetype)initWithEduStanfordNlpOptimizationFunction:(id<EduStanfordNlpOptimizationFunction>)monitor;

- (IOSDoubleArray *)minimizeWithEduStanfordNlpOptimizationFunction:(id<EduStanfordNlpOptimizationDiffFunction>)function
                                                        withDouble:(jdouble)functionTolerance
                                                   withDoubleArray:(IOSDoubleArray *)initial;

- (IOSDoubleArray *)minimizeWithEduStanfordNlpOptimizationFunction:(id<EduStanfordNlpOptimizationDiffFunction>)dFunction
                                                        withDouble:(jdouble)functionTolerance
                                                   withDoubleArray:(IOSDoubleArray *)initial
                                                           withInt:(jint)maxIterations;

- (void)setIterationCallbackFunctionWithEduStanfordNlpUtilCallbackFunction:(EduStanfordNlpUtilCallbackFunction *)func;

#pragma mark Package-Private

+ (IOSDoubleArray *)copyArrayWithDoubleArray:(IOSDoubleArray *)a OBJC_METHOD_FAMILY_NONE;

- (IOSDoubleArray *)lineMinimizeWithEduStanfordNlpOptimizationDiffFunction:(id<EduStanfordNlpOptimizationDiffFunction>)function
                                                           withDoubleArray:(IOSDoubleArray *)initial
                                                           withDoubleArray:(IOSDoubleArray *)direction;

@end

J2OBJC_STATIC_INIT(EduStanfordNlpOptimizationCGMinimizer)

FOUNDATION_EXPORT IOSDoubleArray *EduStanfordNlpOptimizationCGMinimizer_copyArrayWithDoubleArray_(IOSDoubleArray *a);

FOUNDATION_EXPORT void EduStanfordNlpOptimizationCGMinimizer_init(EduStanfordNlpOptimizationCGMinimizer *self);

FOUNDATION_EXPORT EduStanfordNlpOptimizationCGMinimizer *new_EduStanfordNlpOptimizationCGMinimizer_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpOptimizationCGMinimizer *create_EduStanfordNlpOptimizationCGMinimizer_init();

FOUNDATION_EXPORT void EduStanfordNlpOptimizationCGMinimizer_initWithBoolean_(EduStanfordNlpOptimizationCGMinimizer *self, jboolean silent);

FOUNDATION_EXPORT EduStanfordNlpOptimizationCGMinimizer *new_EduStanfordNlpOptimizationCGMinimizer_initWithBoolean_(jboolean silent) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpOptimizationCGMinimizer *create_EduStanfordNlpOptimizationCGMinimizer_initWithBoolean_(jboolean silent);

FOUNDATION_EXPORT void EduStanfordNlpOptimizationCGMinimizer_initWithEduStanfordNlpOptimizationFunction_(EduStanfordNlpOptimizationCGMinimizer *self, id<EduStanfordNlpOptimizationFunction> monitor);

FOUNDATION_EXPORT EduStanfordNlpOptimizationCGMinimizer *new_EduStanfordNlpOptimizationCGMinimizer_initWithEduStanfordNlpOptimizationFunction_(id<EduStanfordNlpOptimizationFunction> monitor) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpOptimizationCGMinimizer *create_EduStanfordNlpOptimizationCGMinimizer_initWithEduStanfordNlpOptimizationFunction_(id<EduStanfordNlpOptimizationFunction> monitor);

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpOptimizationCGMinimizer)

#endif

#if !defined (EduStanfordNlpOptimizationCGMinimizer_OneDimDiffFunction_) && (INCLUDE_ALL_EduStanfordNlpOptimizationCGMinimizer || defined(INCLUDE_EduStanfordNlpOptimizationCGMinimizer_OneDimDiffFunction))
#define EduStanfordNlpOptimizationCGMinimizer_OneDimDiffFunction_

@class IOSDoubleArray;
@protocol EduStanfordNlpOptimizationDiffFunction;

@interface EduStanfordNlpOptimizationCGMinimizer_OneDimDiffFunction : NSObject

#pragma mark Package-Private

- (instancetype)initWithEduStanfordNlpOptimizationDiffFunction:(id<EduStanfordNlpOptimizationDiffFunction>)function
                                               withDoubleArray:(IOSDoubleArray *)initial
                                               withDoubleArray:(IOSDoubleArray *)direction;

- (jdouble)derivativeAtWithDouble:(jdouble)x;

- (jdouble)valueAtWithDouble:(jdouble)x;

@end

J2OBJC_EMPTY_STATIC_INIT(EduStanfordNlpOptimizationCGMinimizer_OneDimDiffFunction)

FOUNDATION_EXPORT void EduStanfordNlpOptimizationCGMinimizer_OneDimDiffFunction_initWithEduStanfordNlpOptimizationDiffFunction_withDoubleArray_withDoubleArray_(EduStanfordNlpOptimizationCGMinimizer_OneDimDiffFunction *self, id<EduStanfordNlpOptimizationDiffFunction> function, IOSDoubleArray *initial, IOSDoubleArray *direction);

FOUNDATION_EXPORT EduStanfordNlpOptimizationCGMinimizer_OneDimDiffFunction *new_EduStanfordNlpOptimizationCGMinimizer_OneDimDiffFunction_initWithEduStanfordNlpOptimizationDiffFunction_withDoubleArray_withDoubleArray_(id<EduStanfordNlpOptimizationDiffFunction> function, IOSDoubleArray *initial, IOSDoubleArray *direction) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpOptimizationCGMinimizer_OneDimDiffFunction *create_EduStanfordNlpOptimizationCGMinimizer_OneDimDiffFunction_initWithEduStanfordNlpOptimizationDiffFunction_withDoubleArray_withDoubleArray_(id<EduStanfordNlpOptimizationDiffFunction> function, IOSDoubleArray *initial, IOSDoubleArray *direction);

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpOptimizationCGMinimizer_OneDimDiffFunction)

#endif

#pragma pop_macro("INCLUDE_ALL_EduStanfordNlpOptimizationCGMinimizer")
