//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/trees/tregex/package-info.java
//

#include "J2ObjC_source.h"
#include "edu/stanford/nlp/trees/tregex/package-info.h"
