//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/objectbank/IteratorFromReaderFactory.java
//

#include "J2ObjC_source.h"
#include "edu/stanford/nlp/objectbank/IteratorFromReaderFactory.h"

@interface EduStanfordNlpObjectbankIteratorFromReaderFactory : NSObject

@end

@implementation EduStanfordNlpObjectbankIteratorFromReaderFactory

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LJavaUtilIterator;", 0x401, 0, 1, -1, 2, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getIteratorWithJavaIoReader:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "getIterator", "LJavaIoReader;", "(Ljava/io/Reader;)Ljava/util/Iterator<TT;>;", "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _EduStanfordNlpObjectbankIteratorFromReaderFactory = { "IteratorFromReaderFactory", "edu.stanford.nlp.objectbank", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, 3, -1 };
  return &_EduStanfordNlpObjectbankIteratorFromReaderFactory;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(EduStanfordNlpObjectbankIteratorFromReaderFactory)
