//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/parser/lexparser/SpanishTreebankParserParams.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "edu/stanford/nlp/ling/Sentence.h"
#include "edu/stanford/nlp/parser/lexparser/BaseLexicon.h"
#include "edu/stanford/nlp/parser/lexparser/Lexicon.h"
#include "edu/stanford/nlp/parser/lexparser/Options.h"
#include "edu/stanford/nlp/parser/lexparser/SpanishTreebankParserParams.h"
#include "edu/stanford/nlp/parser/lexparser/TreeCollinizer.h"
#include "edu/stanford/nlp/parser/lexparser/TregexPoweredTreebankParserParams.h"
#include "edu/stanford/nlp/process/SerializableFunction.h"
#include "edu/stanford/nlp/trees/DiskTreebank.h"
#include "edu/stanford/nlp/trees/HeadFinder.h"
#include "edu/stanford/nlp/trees/MemoryTreebank.h"
#include "edu/stanford/nlp/trees/Tree.h"
#include "edu/stanford/nlp/trees/TreeReaderFactory.h"
#include "edu/stanford/nlp/trees/TreeTransformer.h"
#include "edu/stanford/nlp/trees/TreebankLanguagePack.h"
#include "edu/stanford/nlp/trees/international/spanish/SpanishHeadFinder.h"
#include "edu/stanford/nlp/trees/international/spanish/SpanishTreeReaderFactory.h"
#include "edu/stanford/nlp/trees/international/spanish/SpanishTreebankLanguagePack.h"
#include "edu/stanford/nlp/trees/tregex/TregexMatcher.h"
#include "edu/stanford/nlp/util/Index.h"
#include "edu/stanford/nlp/util/Pair.h"
#include "java/io/PrintStream.h"
#include "java/lang/Exception.h"
#include "java/lang/Math.h"
#include "java/lang/StringBuilder.h"
#include "java/lang/System.h"
#include "java/util/List.h"
#include "java/util/Map.h"
#include "java/util/function/Function.h"

@interface EduStanfordNlpParserLexparserSpanishTreebankParserParams () {
 @public
  JavaLangStringBuilder *optionsString_;
  id<EduStanfordNlpTreesHeadFinder> headFinder_;
}

- (void)buildAnnotations;

@end

J2OBJC_FIELD_SETTER(EduStanfordNlpParserLexparserSpanishTreebankParserParams, optionsString_, JavaLangStringBuilder *)
J2OBJC_FIELD_SETTER(EduStanfordNlpParserLexparserSpanishTreebankParserParams, headFinder_, id<EduStanfordNlpTreesHeadFinder>)

inline jlong EduStanfordNlpParserLexparserSpanishTreebankParserParams_get_serialVersionUID();
#define EduStanfordNlpParserLexparserSpanishTreebankParserParams_serialVersionUID -8734165273482119424LL
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpParserLexparserSpanishTreebankParserParams, serialVersionUID, jlong)

inline NSString *EduStanfordNlpParserLexparserSpanishTreebankParserParams_get_PODER_FORM();
static NSString *EduStanfordNlpParserLexparserSpanishTreebankParserParams_PODER_FORM = @"(?i)^(?:pued(?:o|[ea][sn]?)|pod(?:e[dr]|ido|[ea]mos|[\u00e9\u00e1]is|r(?:\u00e9(?:is)?|\u00e1[sn]?|emos)|r?\u00eda(?:s|mos|is|n)?)|pud(?:[eo]|i(?:ste(?:is)?|mos|eron|er[ea](?:[sn]|is)?|\u00e9r[ea]mos|endo)))$";
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpParserLexparserSpanishTreebankParserParams, PODER_FORM, NSString *)

inline NSString *EduStanfordNlpParserLexparserSpanishTreebankParserParams_get_HACER_TIME_FORM();
static NSString *EduStanfordNlpParserLexparserSpanishTreebankParserParams_HACER_TIME_FORM = @"(?i)^(?:hac(?:er|\u00eda))$";
J2OBJC_STATIC_FIELD_OBJ_FINAL(EduStanfordNlpParserLexparserSpanishTreebankParserParams, HACER_TIME_FORM, NSString *)

__attribute__((unused)) static void EduStanfordNlpParserLexparserSpanishTreebankParserParams_buildAnnotations(EduStanfordNlpParserLexparserSpanishTreebankParserParams *self);

@interface EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction : NSObject < EduStanfordNlpProcessSerializableFunction >

- (NSString *)applyWithId:(EduStanfordNlpTreesTregexTregexMatcher *)m;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction)

inline jlong EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction_get_serialVersionUID();
#define EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction_serialVersionUID 403406212736445856LL
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction, serialVersionUID, jlong)

__attribute__((unused)) static void EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction_init(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction *self);

__attribute__((unused)) static EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction *new_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction *create_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction_init();

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction)

@interface EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction : NSObject < EduStanfordNlpProcessSerializableFunction > {
 @public
  jint prefixLength_;
}

- (instancetype)init;

- (instancetype)initWithInt:(jint)prefixLength;

- (NSString *)applyWithId:(EduStanfordNlpTreesTregexTregexMatcher *)m;

@end

J2OBJC_EMPTY_STATIC_INIT(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction)

inline jlong EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_get_serialVersionUID();
#define EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_serialVersionUID -3275700521562916350LL
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction, serialVersionUID, jlong)

inline jint EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_get_DEFAULT_PREFIX_LENGTH();
#define EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_DEFAULT_PREFIX_LENGTH 3
J2OBJC_STATIC_FIELD_CONSTANT(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction, DEFAULT_PREFIX_LENGTH, jint)

__attribute__((unused)) static void EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_init(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction *self);

__attribute__((unused)) static EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction *new_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction *create_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_init();

__attribute__((unused)) static void EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_initWithInt_(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction *self, jint prefixLength);

__attribute__((unused)) static EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction *new_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_initWithInt_(jint prefixLength) NS_RETURNS_RETAINED;

__attribute__((unused)) static EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction *create_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_initWithInt_(jint prefixLength);

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction)

@implementation EduStanfordNlpParserLexparserSpanishTreebankParserParams

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  EduStanfordNlpParserLexparserSpanishTreebankParserParams_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)buildAnnotations {
  EduStanfordNlpParserLexparserSpanishTreebankParserParams_buildAnnotations(self);
}

- (IOSObjectArray *)baselineAnnotationFeatures {
  return [IOSObjectArray newArrayWithObjects:(id[]){ @"-markInf", @"-markGer", @"-markRightRecVPPrefixes", @"-markSingleChildNPs", @"-markBaseNPs", @"-markPronounNPs", @"-markRelative", @"-markComo", @"-markSpecHeads", @"-markPPFriendlyVerbs", @"-markParticipleAdjs", @"-markHacerTime", @"-markConjTypes", @"-markVerbless", @"-markDominatesVerb" } count:15 type:NSString_class_()];
}

- (id<EduStanfordNlpTreesHeadFinder>)headFinder {
  return headFinder_;
}

- (id<EduStanfordNlpTreesHeadFinder>)typedDependencyHeadFinder {
  return nil;
}

- (id<EduStanfordNlpParserLexparserLexicon>)lexWithEduStanfordNlpParserLexparserOptions:(EduStanfordNlpParserLexparserOptions *)op
                                                            withEduStanfordNlpUtilIndex:(id<EduStanfordNlpUtilIndex>)wordIndex
                                                            withEduStanfordNlpUtilIndex:(id<EduStanfordNlpUtilIndex>)tagIndex {
  if (((EduStanfordNlpParserLexparserOptions_LexOptions *) nil_chk(((EduStanfordNlpParserLexparserOptions *) nil_chk(op))->lexOptions_))->uwModelTrainer_ == nil) op->lexOptions_->uwModelTrainer_ = @"edu.stanford.nlp.parser.lexparser.SpanishUnknownWordModelTrainer";
  return new_EduStanfordNlpParserLexparserBaseLexicon_initWithEduStanfordNlpParserLexparserOptions_withEduStanfordNlpUtilIndex_withEduStanfordNlpUtilIndex_(op, wordIndex, tagIndex);
}

- (IOSObjectArray *)sisterSplitters {
  return [IOSObjectArray newArrayWithLength:0 type:NSString_class_()];
}

- (id<EduStanfordNlpTreesTreeTransformer>)collinizer {
  return new_EduStanfordNlpParserLexparserTreeCollinizer_initWithEduStanfordNlpTreesTreebankLanguagePack_([self treebankLanguagePack]);
}

- (id<EduStanfordNlpTreesTreeTransformer>)collinizerEvalb {
  return new_EduStanfordNlpParserLexparserTreeCollinizer_initWithEduStanfordNlpTreesTreebankLanguagePack_([self treebankLanguagePack]);
}

- (EduStanfordNlpTreesDiskTreebank *)diskTreebank {
  return new_EduStanfordNlpTreesDiskTreebank_initWithEduStanfordNlpTreesTreeReaderFactory_withNSString_([self treeReaderFactory], inputEncoding_);
}

- (EduStanfordNlpTreesMemoryTreebank *)memoryTreebank {
  return new_EduStanfordNlpTreesMemoryTreebank_initWithEduStanfordNlpTreesTreeReaderFactory_withNSString_([self treeReaderFactory], inputEncoding_);
}

- (jint)setOptionFlagWithNSStringArray:(IOSObjectArray *)args
                               withInt:(jint)i {
  if ([((NSString *) nil_chk(IOSObjectArray_Get(nil_chk(args), i))) equalsIgnoreCase:@"-headFinder"] && (i + 1 < args->size_)) {
    @try {
      id<EduStanfordNlpTreesHeadFinder> hf = (id<EduStanfordNlpTreesHeadFinder>) cast_check([((IOSClass *) nil_chk(IOSClass_forName_(IOSObjectArray_Get(args, i + 1)))) newInstance], EduStanfordNlpTreesHeadFinder_class_());
      [self setHeadFinderWithEduStanfordNlpTreesHeadFinder:hf];
      (void) [((JavaLangStringBuilder *) nil_chk(optionsString_)) appendWithNSString:JreStrcat("$$C", @"HeadFinder: ", IOSObjectArray_Get(args, i + 1), 0x000a)];
    }
    @catch (JavaLangException *e) {
      [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, err))) printlnWithId:e];
      [JreLoadStatic(JavaLangSystem, err) printlnWithNSString:JreStrcat("$$$", [[self getClass] getName], @": Could not load head finder ", IOSObjectArray_Get(args, i + 1))];
    }
    i += 2;
  }
  return i;
}

- (id<EduStanfordNlpTreesTreeReaderFactory>)treeReaderFactory {
  return new_EduStanfordNlpTreesInternationalSpanishSpanishTreeReaderFactory_init();
}

- (id<JavaUtilList>)defaultTestSentence {
  IOSObjectArray *sent = [IOSObjectArray newArrayWithObjects:(id[]){ @"\u00c9sto", @"es", @"s\u00f3lo", @"una", @"prueba", @"." } count:6 type:NSString_class_()];
  return EduStanfordNlpLingSentence_toWordListWithNSStringArray_(sent);
}

- (void)display {
  [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, err))) printlnWithNSString:[((JavaLangStringBuilder *) nil_chk(optionsString_)) description]];
  [super display];
}

- (void)setHeadFinderWithEduStanfordNlpTreesHeadFinder:(id<EduStanfordNlpTreesHeadFinder>)hf {
  headFinder_ = hf;
  [self compileAnnotationsWithEduStanfordNlpTreesHeadFinder:headFinder_];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LNSString;", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpTreesHeadFinder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpTreesHeadFinder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpParserLexparserLexicon;", 0x1, 0, 1, -1, 2, -1, -1 },
    { NULL, "[LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpTreesTreeTransformer;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpTreesTreeTransformer;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpTreesDiskTreebank;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpTreesMemoryTreebank;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "LEduStanfordNlpTreesTreeReaderFactory;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 5, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(buildAnnotations);
  methods[2].selector = @selector(baselineAnnotationFeatures);
  methods[3].selector = @selector(headFinder);
  methods[4].selector = @selector(typedDependencyHeadFinder);
  methods[5].selector = @selector(lexWithEduStanfordNlpParserLexparserOptions:withEduStanfordNlpUtilIndex:withEduStanfordNlpUtilIndex:);
  methods[6].selector = @selector(sisterSplitters);
  methods[7].selector = @selector(collinizer);
  methods[8].selector = @selector(collinizerEvalb);
  methods[9].selector = @selector(diskTreebank);
  methods[10].selector = @selector(memoryTreebank);
  methods[11].selector = @selector(setOptionFlagWithNSStringArray:withInt:);
  methods[12].selector = @selector(treeReaderFactory);
  methods[13].selector = @selector(defaultTestSentence);
  methods[14].selector = @selector(display);
  methods[15].selector = @selector(setHeadFinderWithEduStanfordNlpTreesHeadFinder:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = EduStanfordNlpParserLexparserSpanishTreebankParserParams_serialVersionUID, 0x1a, -1, -1, -1, -1 },
    { "optionsString_", "LJavaLangStringBuilder;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "headFinder_", "LEduStanfordNlpTreesHeadFinder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "PODER_FORM", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 8, -1, -1 },
    { "HACER_TIME_FORM", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 9, -1, -1 },
  };
  static const void *ptrTable[] = { "lex", "LEduStanfordNlpParserLexparserOptions;LEduStanfordNlpUtilIndex;LEduStanfordNlpUtilIndex;", "(Ledu/stanford/nlp/parser/lexparser/Options;Ledu/stanford/nlp/util/Index<Ljava/lang/String;>;Ledu/stanford/nlp/util/Index<Ljava/lang/String;>;)Ledu/stanford/nlp/parser/lexparser/Lexicon;", "setOptionFlag", "[LNSString;I", "()Ljava/util/List<Ledu/stanford/nlp/ling/HasWord;>;", "setHeadFinder", "LEduStanfordNlpTreesHeadFinder;", &EduStanfordNlpParserLexparserSpanishTreebankParserParams_PODER_FORM, &EduStanfordNlpParserLexparserSpanishTreebankParserParams_HACER_TIME_FORM, "LEduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction;LEduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction;" };
  static const J2ObjcClassInfo _EduStanfordNlpParserLexparserSpanishTreebankParserParams = { "SpanishTreebankParserParams", "edu.stanford.nlp.parser.lexparser", ptrTable, methods, fields, 7, 0x1, 16, 5, -1, 10, -1, -1, -1 };
  return &_EduStanfordNlpParserLexparserSpanishTreebankParserParams;
}

@end

void EduStanfordNlpParserLexparserSpanishTreebankParserParams_init(EduStanfordNlpParserLexparserSpanishTreebankParserParams *self) {
  EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_initWithEduStanfordNlpTreesTreebankLanguagePack_(self, new_EduStanfordNlpTreesInternationalSpanishSpanishTreebankLanguagePack_init());
  [self setInputEncodingWithNSString:[((id<EduStanfordNlpTreesTreebankLanguagePack>) nil_chk([self treebankLanguagePack])) getEncoding]];
  [self setHeadFinderWithEduStanfordNlpTreesHeadFinder:new_EduStanfordNlpTreesInternationalSpanishSpanishHeadFinder_init()];
  self->optionsString_ = new_JavaLangStringBuilder_init();
  (void) [self->optionsString_ appendWithNSString:JreStrcat("$C", [[self getClass] getSimpleName], 0x000a)];
  EduStanfordNlpParserLexparserSpanishTreebankParserParams_buildAnnotations(self);
}

EduStanfordNlpParserLexparserSpanishTreebankParserParams *new_EduStanfordNlpParserLexparserSpanishTreebankParserParams_init() {
  J2OBJC_NEW_IMPL(EduStanfordNlpParserLexparserSpanishTreebankParserParams, init)
}

EduStanfordNlpParserLexparserSpanishTreebankParserParams *create_EduStanfordNlpParserLexparserSpanishTreebankParserParams_init() {
  J2OBJC_CREATE_IMPL(EduStanfordNlpParserLexparserSpanishTreebankParserParams, init)
}

void EduStanfordNlpParserLexparserSpanishTreebankParserParams_buildAnnotations(EduStanfordNlpParserLexparserSpanishTreebankParserParams *self) {
  (void) [((id<JavaUtilMap>) nil_chk(self->annotations_)) putWithId:@"-markInf" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"/^(S|grup\\.verb|infinitiu|gerundi)/ < @infinitiu", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-infinitive"))];
  (void) [self->annotations_ putWithId:@"-markGer" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"/^(S|grup\\.verb|infinitiu|gerundi)/ < @gerundi", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-gerund"))];
  (void) [self->annotations_ putWithId:@"-markRelative" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"@S <, @relatiu", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-relative"))];
  (void) [self->annotations_ putWithId:@"-markPPHeads" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"@sp", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_AnnotateHeadFunction_initWithEduStanfordNlpTreesHeadFinder_(self->headFinder_))];
  (void) [self->annotations_ putWithId:@"-markComo" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"@cs < /(?i)^como$/", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"[como]"))];
  (void) [self->annotations_ putWithId:@"-markSpecHeads" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"@spec", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_AnnotateHeadFunction_initWithEduStanfordNlpTreesHeadFinder_(self->headFinder_))];
  (void) [self->annotations_ putWithId:@"-markSingleChildNPs" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"/^(sn|grup\\.nom)/ <: __", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-singleChild"))];
  (void) [self->annotations_ putWithId:@"-markPPFriendlyVerbs" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"/^v/ > /^grup\\.prep/", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-PPFriendly"))];
  (void) [self->annotations_ putWithId:@"-markConjTypes" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"@conj <: /^c[cs]/=c", new_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction_init())];
  (void) [self->annotations_ putWithId:@"-markPronounNPs" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"/^(sn|grup\\.nom)/ <<: /^p[0p]/", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-pronoun"))];
  (void) [self->annotations_ putWithId:@"-markParticipleAdjs" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"@aq0000 < /(?i)([aei\u00ed]d|puest|biert|vist|(ben|mal)dit|[fh]ech|scrit|muert|[sv]uelt|[rl]ect|frit|^(rot|dich|impres|desnud|sujet|exent))[oa]s?$/", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-part"))];
  (void) [self->annotations_ putWithId:@"-markSentenceInitialClauses" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"@S !, __", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-init"))];
  (void) [self->annotations_ putWithId:@"-markPoder" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(NSString_formatWithNSString_withNSObjectArray_(@"/^(infinitiu|gerundi|grup\\.verb)/ <<: /%s/", [IOSObjectArray newArrayWithObjects:(id[]){ EduStanfordNlpParserLexparserSpanishTreebankParserParams_PODER_FORM } count:1 type:NSObject_class_()]), new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-poder"))];
  (void) [self->annotations_ putWithId:@"-markBaseNPs" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"/^grup\\.nom/ !< (__ < (__ < __))", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-base"))];
  (void) [self->annotations_ putWithId:@"-markVerbless" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"@S|sentence !<< /^(v|participi$)/", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-verbless"))];
  (void) [self->annotations_ putWithId:@"-markDominatesVerb" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"__ << (/^(v|participi$)/ < __)", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-dominatesV"))];
  (void) [self->annotations_ putWithId:@"-markNonRecSPs" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"@sp !<< @sp", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-nonRec"))];
  (void) [self->annotations_ putWithId:@"-markRightRecVPPrefixes" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"/^v/ $+ @infinitiu|gerundi >, /^(grup.verb|infinitiu|gerundi)/", new_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_initWithInt_(3))];
  (void) [self->annotations_ putWithId:@"-markParentheticalNPs" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"@sn <<, fpa <<` fpt", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-paren"))];
  (void) [self->annotations_ putWithId:@"-markNumericNPs" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"@sn << (/^z/ < __) !<< @sn", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-num"))];
  (void) [self->annotations_ putWithId:@"-markCoordinatedNPs" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(@"@sn <, (/^(sn|grup\\.nom)/ $+ (@conj < /^(cc|grup\\.cc)/ $+ /^(sn|grup\\.nom)/=last))<` =last", new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-coord"))];
  (void) [self->annotations_ putWithId:@"-markHacerTime" withId:new_EduStanfordNlpUtilPair_initWithId_withId_(NSString_formatWithNSString_withNSObjectArray_(@"/^vm/ < /%s/ $+ /^d/", [IOSObjectArray newArrayWithObjects:(id[]){ EduStanfordNlpParserLexparserSpanishTreebankParserParams_HACER_TIME_FORM } count:1 type:NSObject_class_()]), new_EduStanfordNlpParserLexparserTregexPoweredTreebankParserParams_SimpleStringFunction_initWithNSString_(@"-hacerTime"))];
  [self compileAnnotationsWithEduStanfordNlpTreesHeadFinder:self->headFinder_];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduStanfordNlpParserLexparserSpanishTreebankParserParams)

@implementation EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction

- (NSString *)applyWithId:(EduStanfordNlpTreesTregexTregexMatcher *)m {
  NSString *type = [((NSString *) nil_chk([((EduStanfordNlpTreesTree *) nil_chk([((EduStanfordNlpTreesTregexTregexMatcher *) nil_chk(m)) getNodeWithNSString:@"c"])) value])) uppercaseString];
  return JreStrcat("$$", @"-conj", type);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<JavaUtilFunctionFunction>)andThenWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_andThenWithJavaUtilFunctionFunction_(self, arg0);
}

- (id<JavaUtilFunctionFunction>)composeWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_composeWithJavaUtilFunctionFunction_(self, arg0);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(applyWithId:);
  methods[1].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction_serialVersionUID, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "apply", "LEduStanfordNlpTreesTregexTregexMatcher;", "LEduStanfordNlpParserLexparserSpanishTreebankParserParams;", "Ljava/lang/Object;Ledu/stanford/nlp/process/SerializableFunction<Ledu/stanford/nlp/trees/tregex/TregexMatcher;Ljava/lang/String;>;" };
  static const J2ObjcClassInfo _EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction = { "MarkConjTypeFunction", "edu.stanford.nlp.parser.lexparser", ptrTable, methods, fields, 7, 0xa, 2, 1, 2, -1, -1, 3, -1 };
  return &_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction;
}

@end

void EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction_init(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction *self) {
  NSObject_init(self);
}

EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction *new_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction_init() {
  J2OBJC_NEW_IMPL(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction, init)
}

EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction *create_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction_init() {
  J2OBJC_CREATE_IMPL(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkConjTypeFunction)

@implementation EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithInt:(jint)prefixLength {
  EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_initWithInt_(self, prefixLength);
  return self;
}

- (NSString *)applyWithId:(EduStanfordNlpTreesTregexTregexMatcher *)m {
  EduStanfordNlpTreesTree *tagNode = [((EduStanfordNlpTreesTregexTregexMatcher *) nil_chk(m)) getMatch];
  NSString *yield = [((EduStanfordNlpTreesTree *) nil_chk([((EduStanfordNlpTreesTree *) nil_chk(tagNode)) firstChild])) value];
  NSString *prefix = [((NSString *) nil_chk(yield)) substring:0 endIndex:JavaLangMath_minWithInt_withInt_(((jint) [yield length]), prefixLength_)];
  return JreStrcat("$$C", @"[p,", prefix, ']');
}

- (id<JavaUtilFunctionFunction>)andThenWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_andThenWithJavaUtilFunctionFunction_(self, arg0);
}

- (id<JavaUtilFunctionFunction>)composeWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_composeWithJavaUtilFunctionFunction_(self, arg0);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithInt:);
  methods[2].selector = @selector(applyWithId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_serialVersionUID, 0x1a, -1, -1, -1, -1 },
    { "DEFAULT_PREFIX_LENGTH", "I", .constantValue.asInt = EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_DEFAULT_PREFIX_LENGTH, 0x1a, -1, -1, -1, -1 },
    { "prefixLength_", "I", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "I", "apply", "LEduStanfordNlpTreesTregexTregexMatcher;", "LEduStanfordNlpParserLexparserSpanishTreebankParserParams;", "Ljava/lang/Object;Ledu/stanford/nlp/process/SerializableFunction<Ledu/stanford/nlp/trees/tregex/TregexMatcher;Ljava/lang/String;>;" };
  static const J2ObjcClassInfo _EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction = { "MarkPrefixFunction", "edu.stanford.nlp.parser.lexparser", ptrTable, methods, fields, 7, 0xa, 3, 3, 3, -1, -1, 4, -1 };
  return &_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction;
}

@end

void EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_init(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction *self) {
  EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_initWithInt_(self, EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_DEFAULT_PREFIX_LENGTH);
}

EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction *new_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_init() {
  J2OBJC_NEW_IMPL(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction, init)
}

EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction *create_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_init() {
  J2OBJC_CREATE_IMPL(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction, init)
}

void EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_initWithInt_(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction *self, jint prefixLength) {
  NSObject_init(self);
  self->prefixLength_ = prefixLength;
}

EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction *new_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_initWithInt_(jint prefixLength) {
  J2OBJC_NEW_IMPL(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction, initWithInt_, prefixLength)
}

EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction *create_EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction_initWithInt_(jint prefixLength) {
  J2OBJC_CREATE_IMPL(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction, initWithInt_, prefixLength)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduStanfordNlpParserLexparserSpanishTreebankParserParams_MarkPrefixFunction)
