//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/parser/lexparser/TagProjection.java
//

#include "J2ObjC_source.h"
#include "edu/stanford/nlp/parser/lexparser/TagProjection.h"

@interface EduStanfordNlpParserLexparserTagProjection : NSObject

@end

@implementation EduStanfordNlpParserLexparserTagProjection

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x401, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(projectWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "project", "LNSString;" };
  static const J2ObjcClassInfo _EduStanfordNlpParserLexparserTagProjection = { "TagProjection", "edu.stanford.nlp.parser.lexparser", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_EduStanfordNlpParserLexparserTagProjection;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(EduStanfordNlpParserLexparserTagProjection)
