//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/sequences/package-info.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduStanfordNlpSequencesPackage_info")
#ifdef RESTRICT_EduStanfordNlpSequencesPackage_info
#define INCLUDE_ALL_EduStanfordNlpSequencesPackage_info 0
#else
#define INCLUDE_ALL_EduStanfordNlpSequencesPackage_info 1
#endif
#undef RESTRICT_EduStanfordNlpSequencesPackage_info

#pragma pop_macro("INCLUDE_ALL_EduStanfordNlpSequencesPackage_info")
