//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/stats/SimpleGoodTuring.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduStanfordNlpStatsSimpleGoodTuring")
#ifdef RESTRICT_EduStanfordNlpStatsSimpleGoodTuring
#define INCLUDE_ALL_EduStanfordNlpStatsSimpleGoodTuring 0
#else
#define INCLUDE_ALL_EduStanfordNlpStatsSimpleGoodTuring 1
#endif
#undef RESTRICT_EduStanfordNlpStatsSimpleGoodTuring

#if !defined (EduStanfordNlpStatsSimpleGoodTuring_) && (INCLUDE_ALL_EduStanfordNlpStatsSimpleGoodTuring || defined(INCLUDE_EduStanfordNlpStatsSimpleGoodTuring))
#define EduStanfordNlpStatsSimpleGoodTuring_

@class IOSDoubleArray;
@class IOSIntArray;
@class IOSObjectArray;

@interface EduStanfordNlpStatsSimpleGoodTuring : NSObject

#pragma mark Public

- (instancetype)initWithIntArray:(IOSIntArray *)r
                    withIntArray:(IOSIntArray *)n;

- (IOSDoubleArray *)getProbabilities;

- (jdouble)getProbabilityForUnseen;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

@end

J2OBJC_EMPTY_STATIC_INIT(EduStanfordNlpStatsSimpleGoodTuring)

FOUNDATION_EXPORT void EduStanfordNlpStatsSimpleGoodTuring_initWithIntArray_withIntArray_(EduStanfordNlpStatsSimpleGoodTuring *self, IOSIntArray *r, IOSIntArray *n);

FOUNDATION_EXPORT EduStanfordNlpStatsSimpleGoodTuring *new_EduStanfordNlpStatsSimpleGoodTuring_initWithIntArray_withIntArray_(IOSIntArray *r, IOSIntArray *n) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpStatsSimpleGoodTuring *create_EduStanfordNlpStatsSimpleGoodTuring_initWithIntArray_withIntArray_(IOSIntArray *r, IOSIntArray *n);

FOUNDATION_EXPORT void EduStanfordNlpStatsSimpleGoodTuring_mainWithNSStringArray_(IOSObjectArray *args);

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpStatsSimpleGoodTuring)

#endif

#pragma pop_macro("INCLUDE_ALL_EduStanfordNlpStatsSimpleGoodTuring")
