//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/semgraph/semgrex/CoordinationPattern.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduStanfordNlpSemgraphSemgrexCoordinationPattern")
#ifdef RESTRICT_EduStanfordNlpSemgraphSemgrexCoordinationPattern
#define INCLUDE_ALL_EduStanfordNlpSemgraphSemgrexCoordinationPattern 0
#else
#define INCLUDE_ALL_EduStanfordNlpSemgraphSemgrexCoordinationPattern 1
#endif
#undef RESTRICT_EduStanfordNlpSemgraphSemgrexCoordinationPattern

#if !defined (EduStanfordNlpSemgraphSemgrexCoordinationPattern_) && (INCLUDE_ALL_EduStanfordNlpSemgraphSemgrexCoordinationPattern || defined(INCLUDE_EduStanfordNlpSemgraphSemgrexCoordinationPattern))
#define EduStanfordNlpSemgraphSemgrexCoordinationPattern_

#define RESTRICT_EduStanfordNlpSemgraphSemgrexSemgrexPattern 1
#define INCLUDE_EduStanfordNlpSemgraphSemgrexSemgrexPattern 1
#include "edu/stanford/nlp/semgraph/semgrex/SemgrexPattern.h"

@class EduStanfordNlpLingIndexedWord;
@class EduStanfordNlpSemgraphSemanticGraph;
@class EduStanfordNlpSemgraphSemgrexAlignment;
@class EduStanfordNlpSemgraphSemgrexSemgrexMatcher;
@class EduStanfordNlpSemgraphSemgrexVariableStrings;
@protocol JavaUtilList;
@protocol JavaUtilMap;

@interface EduStanfordNlpSemgraphSemgrexCoordinationPattern : EduStanfordNlpSemgraphSemgrexSemgrexPattern

#pragma mark Public

- (instancetype)initWithBoolean:(jboolean)isNodeCoord
               withJavaUtilList:(id<JavaUtilList>)children
                    withBoolean:(jboolean)isConj;

- (void)addRelnToNodeCoordWithEduStanfordNlpSemgraphSemgrexSemgrexPattern:(EduStanfordNlpSemgraphSemgrexSemgrexPattern *)child;

- (id<JavaUtilList>)getChildren;

- (jboolean)isNodeCoord;

- (NSString *)localString;

- (EduStanfordNlpSemgraphSemgrexSemgrexMatcher *)matcherWithEduStanfordNlpSemgraphSemanticGraph:(EduStanfordNlpSemgraphSemanticGraph *)sg
                                                     withEduStanfordNlpSemgraphSemgrexAlignment:(EduStanfordNlpSemgraphSemgrexAlignment *)alignment
                                                        withEduStanfordNlpSemgraphSemanticGraph:(EduStanfordNlpSemgraphSemanticGraph *)sg_align
                                                                                    withBoolean:(jboolean)hypToText
                                                              withEduStanfordNlpLingIndexedWord:(EduStanfordNlpLingIndexedWord *)node
                                                                                withJavaUtilMap:(id<JavaUtilMap>)namesToNodes
                                                                                withJavaUtilMap:(id<JavaUtilMap>)namesToRelations
                                               withEduStanfordNlpSemgraphSemgrexVariableStrings:(EduStanfordNlpSemgraphSemgrexVariableStrings *)variableStrings
                                                                                    withBoolean:(jboolean)ignoreCase;

- (EduStanfordNlpSemgraphSemgrexSemgrexMatcher *)matcherWithEduStanfordNlpSemgraphSemanticGraph:(EduStanfordNlpSemgraphSemanticGraph *)sg
                                                              withEduStanfordNlpLingIndexedWord:(EduStanfordNlpLingIndexedWord *)node
                                                                                withJavaUtilMap:(id<JavaUtilMap>)namesToNodes
                                                                                withJavaUtilMap:(id<JavaUtilMap>)namesToRelations
                                               withEduStanfordNlpSemgraphSemgrexVariableStrings:(EduStanfordNlpSemgraphSemgrexVariableStrings *)variableStrings
                                                                                    withBoolean:(jboolean)ignoreCase;

- (void)setChildWithEduStanfordNlpSemgraphSemgrexSemgrexPattern:(EduStanfordNlpSemgraphSemgrexSemgrexPattern *)child;

- (NSString *)description;

- (NSString *)toStringWithBoolean:(jboolean)hasPrecedence;

@end

J2OBJC_EMPTY_STATIC_INIT(EduStanfordNlpSemgraphSemgrexCoordinationPattern)

FOUNDATION_EXPORT void EduStanfordNlpSemgraphSemgrexCoordinationPattern_initWithBoolean_withJavaUtilList_withBoolean_(EduStanfordNlpSemgraphSemgrexCoordinationPattern *self, jboolean isNodeCoord, id<JavaUtilList> children, jboolean isConj);

FOUNDATION_EXPORT EduStanfordNlpSemgraphSemgrexCoordinationPattern *new_EduStanfordNlpSemgraphSemgrexCoordinationPattern_initWithBoolean_withJavaUtilList_withBoolean_(jboolean isNodeCoord, id<JavaUtilList> children, jboolean isConj) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduStanfordNlpSemgraphSemgrexCoordinationPattern *create_EduStanfordNlpSemgraphSemgrexCoordinationPattern_initWithBoolean_withJavaUtilList_withBoolean_(jboolean isNodeCoord, id<JavaUtilList> children, jboolean isConj);

J2OBJC_TYPE_LITERAL_HEADER(EduStanfordNlpSemgraphSemgrexCoordinationPattern)

#endif

#pragma pop_macro("INCLUDE_ALL_EduStanfordNlpSemgraphSemgrexCoordinationPattern")
