//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stanford-postagger-java/edu/stanford/nlp/semgraph/semgrex/SemgrexParseException.java
//

#include "J2ObjC_source.h"
#include "edu/stanford/nlp/semgraph/semgrex/SemgrexParseException.h"
#include "java/lang/RuntimeException.h"

@implementation EduStanfordNlpSemgraphSemgrexSemgrexParseException

- (instancetype)initWithNSString:(NSString *)message
                 withNSException:(NSException *)cause {
  EduStanfordNlpSemgraphSemgrexSemgrexParseException_initWithNSString_withNSException_(self, message, cause);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithNSString:withNSException:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;LNSException;" };
  static const J2ObjcClassInfo _EduStanfordNlpSemgraphSemgrexSemgrexParseException = { "SemgrexParseException", "edu.stanford.nlp.semgraph.semgrex", ptrTable, methods, NULL, 7, 0x1, 1, 0, -1, -1, -1, -1, -1 };
  return &_EduStanfordNlpSemgraphSemgrexSemgrexParseException;
}

@end

void EduStanfordNlpSemgraphSemgrexSemgrexParseException_initWithNSString_withNSException_(EduStanfordNlpSemgraphSemgrexSemgrexParseException *self, NSString *message, NSException *cause) {
  JavaLangRuntimeException_initWithNSString_withNSException_(self, message, cause);
}

EduStanfordNlpSemgraphSemgrexSemgrexParseException *new_EduStanfordNlpSemgraphSemgrexSemgrexParseException_initWithNSString_withNSException_(NSString *message, NSException *cause) {
  J2OBJC_NEW_IMPL(EduStanfordNlpSemgraphSemgrexSemgrexParseException, initWithNSString_withNSException_, message, cause)
}

EduStanfordNlpSemgraphSemgrexSemgrexParseException *create_EduStanfordNlpSemgraphSemgrexSemgrexParseException_initWithNSString_withNSException_(NSString *message, NSException *cause) {
  J2OBJC_CREATE_IMPL(EduStanfordNlpSemgraphSemgrexSemgrexParseException, initWithNSString_withNSException_, message, cause)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduStanfordNlpSemgraphSemgrexSemgrexParseException)
